import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {DatabaseSync} from 'node:sqlite';import {scryptSync} from 'node:crypto';import {spawn} from 'node:child_process';import {publishedCurrentFiles} from '../shared/current-files.js';import {sanitizeRelease} from '../scripts/public-access.js';
const root=path.resolve(import.meta.dirname,'..');
test('Подписки и персональные данные: изолированная база',{timeout:60000},async t=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'navigator-accounts-')),db=new DatabaseSync(path.join(dir,'navigator.sqlite'));for(const f of fs.readdirSync(path.join(root,'migrations')).sort())db.exec(fs.readFileSync(path.join(root,'migrations',f),'utf8'));
 const password='test-only-password-2026';for(const name of ['reader','other','admin','editor'])db.prepare('INSERT INTO users VALUES(?,?,?,?,?)').run(name,name,['admin','editor'].includes(name)?name:'reader','test-salt',scryptSync(password,'test-salt',64).toString('hex'));
 const material={id:'paid',kind:'card',status:'published',title:'Закрытая инструкция',profession:'test',accessLevel:'subscriber',steps:[{id:'s1',text:'Текстсекрет',attachments:[]}],blocks:[{text:'Текстсекрет'}],attachments:[],fileId:'file',formReview:{currentFile:'delay-act.docx'}};db.prepare('INSERT INTO materials VALUES(?,?,?,?,?,?,?,?)').run('paid','file','P-1','test','card','published',1,JSON.stringify(material));fs.mkdirSync(path.join(dir,'handoff'));fs.writeFileSync(path.join(dir,'handoff','form.pdf'),'%PDF-private');db.prepare('INSERT INTO sources VALUES(?,?,?)').run('file','hash',JSON.stringify({id:'file',path:'form.pdf',kind:'form'}));
 let child;const base='http://127.0.0.1:4319';const start=async()=>{child=spawn(process.execPath,['server/index.js'],{cwd:root,env:{...process.env,PORT:'4319',DATA_DIR:dir},stdio:'pipe'});await new Promise((r,j)=>{child.stdout.once('data',r);child.once('error',j);child.once('exit',c=>j(Error('server exit '+c)));setTimeout(()=>j(Error('timeout')),10000).unref()})};const stop=async()=>{const done=new Promise(r=>child.once('exit',r));child.kill();await done};await start();
 const req=(url,h={},method='GET',body)=>fetch(base+url,{method,headers:h,body:body===undefined?undefined:JSON.stringify(body)});const login=async username=>{const r=await req('/api/login',{'content-type':'application/json'},'POST',{username,password});assert.equal(r.status,200);const j=await r.json();return {'content-type':'application/json',cookie:r.headers.get('set-cookie').split(';')[0],'x-csrf-token':j.csrf}};
 try{const reader=await login('reader'),other=await login('other'),admin=await login('admin'),editor=await login('editor');
 await t.test('Закрытый текст не утекает в API, поиск, файлы и статическое зеркало',async()=>{assert.equal((await req('/api/materials/paid')).status,402);assert.equal((await req('/files/file')).status,404);assert.equal((await req('/current/delay-act.docx')).status,404);assert.equal((await req('/api/relations/paid')).status,402);assert.equal((await(await req('/api/materials?q=Текстсекрет')).json()).total,0);const list=await(await req('/api/materials?admin=1')).json();assert.equal(list.items[0].locked,true);assert.ok(!JSON.stringify(list).includes('Текстсекрет'));const safe=sanitizeRelease({materials:[material],files:{file:'.pdf'},relations:[]});assert.ok(!JSON.stringify(safe).includes('Текстсекрет'));assert.deepEqual(safe.files,{});assert.equal(publishedCurrentFiles(safe.materials).size,0);assert.equal((await req('/api/materials/paid',editor)).status,200)});
 await t.test('Права и защита CSRF',async()=>{assert.equal((await req('/api/admin/accounts',reader)).status,403);assert.equal((await req('/api/admin/accounts',editor)).status,403);assert.equal((await req('/api/admin/subscriptions/reader',reader,'POST',{planId:'personal',reason:'test'})).status,403);assert.equal((await req('/api/account/access-request',{'content-type':'application/json',cookie:reader.cookie},'POST',{planId:'personal'})).status,403)});
 await t.test('Заявка, дубликат, выдача и сохранение при перезапуске',async()=>{assert.equal((await req('/api/account/access-request',reader,'POST',{planId:'personal'})).status,201);assert.equal((await req('/api/account/access-request',reader,'POST',{planId:'personal'})).status,409);assert.equal((await req('/api/admin/subscriptions/reader',admin,'POST',{planId:'personal',reason:'Пилотный доступ'})).status,200);assert.equal((await req('/api/materials/paid',reader)).status,200);assert.equal((await req('/files/file',reader)).status,200);assert.equal((await req('/current/delay-act.docx',reader)).status,200);assert.equal((await req('/api/materials/paid',other)).status,402);await stop();await start();assert.equal((await req('/api/materials/paid',reader)).status,200);assert.equal((await(await req('/api/account',reader)).json()).requests[0].status,'approved')});
 await t.test('Истечение и отзыв действительно закрывают доступ',async()=>{db.prepare('UPDATE subscriptions SET ends_at=? WHERE user_id=?').run(Date.now()-1,'reader');assert.equal((await req('/api/materials/paid',reader)).status,402);assert.equal((await req('/files/file',reader)).status,404);assert.equal((await req('/current/delay-act.docx',reader)).status,404);await req('/api/admin/subscriptions/reader',admin,'POST',{planId:'personal',reason:'Продление'});assert.equal((await req('/api/admin/subscriptions/reader/revoke',admin,'POST',{reason:'Окончание пилота'})).status,200);assert.equal((await req('/api/materials/paid',reader)).status,402)});
 await t.test('Обращения и выгрузка изолированы, ответ сохраняется',async()=>{const r=await req('/api/account/privacy-request',reader,'POST',{kind:'correction',message:'Исправить данные'});assert.equal(r.status,201);const {id}=await r.json();assert.equal((await(await req('/api/account',other)).json()).privacyRequests.length,0);assert.equal((await req('/api/admin/privacy-requests/'+id+'/resolve',admin,'POST',{response:'Данные проверены'})).status,200);const e=await(await req('/api/account/export',reader)).json();assert.equal(e.user.id,'reader');assert.ok(!JSON.stringify(e).includes('test-salt'));assert.equal(e.privacyRequests[0].response,'Данные проверены')});
 await t.test('Удаление выполняется только по обращению и подтверждённому логину',async()=>{const {id}=await(await req('/api/account/privacy-request',other,'POST',{kind:'deletion'})).json();assert.equal((await req('/api/admin/privacy-requests/'+id+'/resolve',admin,'POST',{response:'Удалено',deleteAccount:true,confirmation:'wrong'})).status,400);assert.equal((await req('/api/admin/privacy-requests/'+id+'/resolve',admin,'POST',{response:'Удалено',deleteAccount:true,confirmation:'other'})).status,200);assert.equal((await req('/api/account',other)).status,401);assert.equal(db.prepare("SELECT count(*) n FROM users WHERE id='other'").get().n,0)});
 await t.test('Смена пароля проверяет текущий и завершает другие сеансы',async()=>{const extra=await login('reader');assert.equal((await req('/api/account/password',reader,'POST',{currentPassword:'bad',password:'another-test-password'})).status,403);assert.equal((await req('/api/account/password',reader,'POST',{currentPassword:password,password:'another-test-password'})).status,200);assert.equal((await req('/api/account',extra)).status,401);assert.equal((await req('/api/account',reader)).status,200)});
 }finally{await stop();db.close();fs.rmSync(dir,{recursive:true,force:true})}
});
