import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {spawn,execFileSync} from 'node:child_process';import {createHash} from 'node:crypto';
const root=path.resolve(import.meta.dirname,'..'),base='http://127.0.0.1:4318';let server;
async function start(){server=spawn(process.execPath,['server/index.js'],{cwd:root,env:{...process.env,PORT:'4318'},stdio:'pipe'});await new Promise((resolve,reject)=>{server.stdout.once('data',resolve);server.once('error',reject);setTimeout(()=>reject(Error('server timeout')),10000).unref()});}
async function stop(){if(server){server.kill();await new Promise(r=>server.once('exit',r));}}
async function login(name){const c=JSON.parse(fs.readFileSync(path.join(root,'private/credentials.json'))).find(x=>x.username===name);const r=await fetch(base+'/api/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(c)});assert.equal(r.status,200);const d=await r.json();return {'content-type':'application/json',cookie:r.headers.get('set-cookie').split(';')[0],'x-csrf-token':d.csrf};}
const req=async(url,headers={},method='GET',body)=>fetch(base+url,{headers,method,body:body?JSON.stringify(body):undefined});
test('Серверные сценарии, права, импорт и восстановление',{timeout:120000},async t=>{
 await start();const reader=await login('reader'),reader2=await login('reader2'),editor=await login('editor'),admin=await login('admin');let original;
 try{
 await t.test('65 источников, 8075 блоков, 14 профессий',async()=>{const s=await(await req('/api/admin/stats',editor)).json();assert.equal(s.sources,65);assert.equal(s.blocks,8075);assert.equal((await(await req('/api/catalog')).json()).length,14);});
 await t.test('Поиск по коду и приватность HR/журналистики',async()=>{const r=await(await req('/api/materials?q=GD-A-01&kind=card')).json();assert.ok(r.items.some(m=>m.code==='GD-A-01'));assert.equal((await(await req('/api/materials?profession=journalism-ip')).json()).total,16);assert.equal((await req('/api/admin/sources',reader)).status,403);assert.equal((await req('/files/SRC-059')).status,404);assert.equal((await req('/api/materials/SRC-036-task-SMI-A-01')).status,404);});
 await t.test('Оригиналы гендиректора, логиста и НКО побайтно совпадают',async()=>{const manifest=JSON.parse(fs.readFileSync(path.join(root,'private/handoff/inventory/manifest.json')));for(const id of ['SRC-039','SRC-054','SRC-065']){const r=await req('/files/'+id+'?download=1');assert.equal(r.status,200);assert.equal(createHash('sha256').update(Buffer.from(await r.arrayBuffer())).digest('hex'),manifest.find(s=>s.id===id).sha256);}});
 original=await(await req('/api/materials/SRC-002-GD-A-01',editor)).json();
 await t.test('Пользовательские данные изолированы',async()=>{for(const [kind,id,data] of [['progress',original.id,{current:1,done:[original.steps[0].id]}],['favorite',original.id,{}],['task','qa-task',{title:'Проверить сохранение',due:'2020-01-01',done:false}]])assert.equal((await req('/api/personal/'+kind+'/'+id,reader,'PUT',data)).status,200);const a=await(await req('/api/personal',reader)).json(),b=await(await req('/api/personal',reader2)).json();assert.ok(a.items.some(i=>i.item==='qa-task'));assert.ok(!b.items.some(i=>i.item==='qa-task'));const n=a.notifications.find(n=>n.title.includes('Проверить сохранение'));assert.ok(n);await req('/api/notifications/'+n.id,reader,'PUT',{});});
 await t.test('Неверный шаг и отсутствующий пользователь отклоняются',async()=>{assert.equal((await req('/api/personal/progress/'+original.id,reader,'PUT',{current:-1,done:[]})).status,400);assert.equal((await req('/api/admin/users/nonexistent',admin,'PUT',{role:'reader'})).status,404);});
 await t.test('Редактура, конфликт 409, скрытие, повторный импорт',async()=>{assert.equal((await req('/api/admin/materials/'+original.id,reader,'PUT',original)).status,403);const changed=await(await req('/api/admin/materials/'+original.id,editor,'PUT',{...original,status:'review',title:original.title+' [QA]'})).json();assert.equal((await req('/api/admin/materials/'+original.id,editor,'PUT',original)).status,409);assert.equal((await req('/api/materials/'+original.id)).status,404);const imported=await(await req('/api/admin/import',admin,'POST',{dryRun:false})).json();assert.equal(imported.unchanged,65);const saved=await(await req('/api/materials/'+original.id,editor)).json();assert.equal(saved.title,changed.title);assert.equal((await req('/api/admin/materials/'+original.id,editor,'PUT',{...original,revision:saved.revision})).status,200);});
 await t.test('CSRF и приватный источник нельзя опубликовать',async()=>{assert.equal((await req('/api/personal/task/no',{'content-type':'application/json',cookie:reader.cookie},'PUT',{title:'bad'})).status,403);const m=await(await req('/api/materials/SRC-036-task-SMI-A-01',editor)).json();assert.equal((await req('/api/admin/materials/'+m.id,editor,'PUT',{...m,kind:'card',status:'published'})).status,400);assert.equal((await req('/api/admin/import',reader,'POST',{dryRun:false})).status,403);});
 await t.test('Перезапуск, повторный вход, прогресс/избранное/задача/прочтение',async()=>{await stop();await start();const h=await login('reader');const a=await(await req('/api/personal',h)).json();assert.ok(a.items.find(i=>i.kind==='progress'&&i.item===original.id).data.done.includes(original.steps[0].id));assert.ok(a.items.some(i=>i.kind==='favorite'&&i.item===original.id));assert.ok(a.items.some(i=>i.item==='qa-task'));assert.ok(a.notifications.some(n=>n.read&&n.title.includes('Проверить сохранение')));});
 await t.test('Резервная копия и восстановление в новый каталог',async()=>{const backup=path.join(root,'work/test-backup-'+Date.now()),restore=backup+'-restored';execFileSync(process.execPath,['scripts/backup.js',backup],{cwd:root});execFileSync(process.execPath,['scripts/backup.js','restore',backup,restore],{cwd:root});assert.ok(fs.existsSync(path.join(restore,'navigator.sqlite')));assert.ok(fs.existsSync(path.join(restore,'handoff/inventory/manifest.json')));});
 }finally{await stop();}
});
