import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {DatabaseSync} from 'node:sqlite';import {scryptSync} from 'node:crypto';import {spawn} from 'node:child_process';import {documentExtension} from '../shared/upload-validation.js';import {helpAnswer} from '../shared/site-help.js';
test('Загрузка распознаёт DOCX, PDF и отвергает другой формат',()=>{assert.equal(documentExtension('акт.docx',fs.readFileSync('public/release/current/delay-act.docx')),'.docx');assert.equal(documentExtension('форма.pdf',fs.readFileSync('public/release/current/R34001.pdf')),'.pdf');for(const name of ['x.html','../x.pdf','x.docx','x.pdf'])assert.throws(()=>documentExtension(name,Buffer.from('<script>alert(1)</script>')))});
test('Помощник отправляет правовой вопрос человеку и объясняет режим зеркала',()=>{assert.equal(helpAnswer('Задать правовой вопрос').links[0].href,'#/legal-question');assert.match(helpAnswer('Как загрузить документ?',true).text,/не принимает данные/);assert.equal(helpAnswer('Где новости?').links[0].href,'#/changes')});
test('Документы и правовые вопросы: серверные права и сохранность',{timeout:60000},async t=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'navigator-support-')),database=new DatabaseSync(path.join(dir,'navigator.sqlite'));for(const f of fs.readdirSync('migrations').sort())database.exec(fs.readFileSync('migrations/'+f,'utf8'));const password='qa-only-password';for(const role of ['reader','other','editor','admin'])database.prepare('INSERT INTO users VALUES(?,?,?,?,?)').run(role,role,['reader','other'].includes(role)?'reader':role,'salt',scryptSync(password,'salt',64).toString('hex'));database.prepare('INSERT INTO professions VALUES(?,?)').run('hr',JSON.stringify({id:'hr',title:'Кадры'}));
 let server;const base='http://127.0.0.1:4323';async function start(){server=spawn(process.execPath,['server/index.js'],{env:{...process.env,PORT:'4323',DATA_DIR:dir,CHANGES_AUTO_SYNC:'0'},stdio:'pipe'});await new Promise((r,j)=>{server.stdout.once('data',r);server.once('exit',c=>j(Error('server '+c)));server.once('error',j)})}async function stop(){const done=new Promise(r=>server.once('exit',r));server.kill();await done}await start();
 const login=async username=>{const r=await fetch(base+'/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username,password})}),body=await r.json();return {'Content-Type':'application/json',Cookie:r.headers.get('set-cookie').split(';')[0],'X-CSRF-Token':body.csrf}};
 const request=(url,headers={},method='GET',body)=>fetch(base+url,{method,headers,body:body===undefined?undefined:JSON.stringify(body)});let q,document;const reader=await login('reader'),other=await login('other'),editor=await login('editor'),admin=await login('admin');
 try{
 await t.test('Файл создаётся черновиком, права проверяются до публикации',async()=>{const bytes=fs.readFileSync('public/release/current/delay-act.docx'),url='/api/admin/documents?'+new URLSearchParams({name:'акт.docx',profession:'hr',title:'Загруженный акт'});assert.equal((await fetch(base+url,{method:'POST',headers:{...reader,'Content-Type':'application/octet-stream'},body:bytes})).status,403);const r=await fetch(base+url,{method:'POST',headers:{...editor,'Content-Type':'application/octet-stream'},body:bytes});assert.equal(r.status,201);document=await r.json();assert.equal(document.status,'draft');assert.equal(document.profession,'hr');assert.equal((await request('/files/'+document.fileId)).status,404);assert.deepEqual(Buffer.from(await(await request('/files/'+document.fileId,editor)).arrayBuffer()),bytes);assert.equal((await request('/api/admin/materials/'+document.id,editor,'PUT',{...document,status:'published'})).status,200);assert.equal((await request('/files/'+document.fileId)).status,200)});
 await t.test('Вопрос принадлежит автору, черновик ответа скрыт, роли ограничены',async()=>{assert.equal((await request('/api/legal-questions')).status,401);const r=await request('/api/legal-questions',reader,'POST',{title:'Вопрос QA',profession:'hr',question:'Проверка правового вопроса',user_id:'other'});assert.equal(r.status,201);q=await r.json();assert.equal(q.user_id,'reader');assert.equal((await(await request('/api/legal-questions',other)).json()).length,0);assert.equal((await request('/api/admin/legal-questions',reader)).status,403);const saved=await request('/api/admin/legal-questions/'+q.id,editor,'PUT',{revision:q.revision,status:'in_progress',response:'Редакторский черновик'});assert.equal(saved.status,200);q=await saved.json();assert.equal((await(await request('/api/legal-questions',reader)).json())[0].response,'');assert.equal((await(await request('/api/account/export',reader)).json()).legalQuestions[0].response,'')});
 await t.test('Проверка ревизии, ответ пользователю и уведомление',async()=>{assert.equal((await request('/api/admin/legal-questions/'+q.id,editor,'PUT',{revision:1,status:'answered',response:'Старая версия'})).status,409);assert.equal((await request('/api/admin/legal-questions/'+q.id,editor,'PUT',{revision:q.revision,status:'answered',response:''})).status,400);assert.equal((await request('/api/admin/legal-questions/'+q.id,editor,'PUT',{revision:q.revision,status:'answered',response:'Ответ после проверки редактором'})).status,200);const own=await(await request('/api/legal-questions',reader)).json();assert.equal(own[0].response,'Ответ после проверки редактором');const notices=await(await request('/api/personal',reader)).json();assert.ok(notices.notifications.some(n=>n.questionId===q.id));assert.equal((await(await request('/api/legal-questions',other)).json()).length,0)});
 await t.test('Документ и ответ сохраняются при перезапуске',async()=>{await stop();await start();assert.equal((await request('/files/'+document.fileId)).status,200);assert.equal((await(await request('/api/legal-questions',reader)).json())[0].status,'answered')});
 await t.test('Удаление учётной записи удаляет её правовые вопросы',async()=>{const deletion=await(await request('/api/account/privacy-request',reader,'POST',{kind:'deletion'})).json();assert.equal((await request('/api/admin/privacy-requests/'+deletion.id+'/resolve',admin,'POST',{response:'Удалено',deleteAccount:true,confirmation:'reader'})).status,200);assert.equal(database.prepare('SELECT count(*) n FROM legal_questions WHERE user_id=?').get('reader').n,0)});
 }finally{await stop();database.close();fs.rmSync(dir,{recursive:true,force:true})}
});
