import {visibleQuestion} from './legal-questions.js';
import {randomUUID,randomBytes,scryptSync,timingSafeEqual} from 'node:crypto';
import {db,all,one,run} from './db.js';
import {operatorDefaults} from '../shared/operator.js';
const fail=(res,status,error)=>res.status(status).json({error});
const audit=(actor,action,target,details={})=>run('INSERT INTO account_audit(actor_id,action,target_id,created_at,details) VALUES(?,?,?,?,?)',actor,action,target,Date.now(),JSON.stringify(details));
const text=(v,max=1000)=>typeof v==='string'&&v.trim().length>0&&v.length<=max;
export const staff=user=>['editor','admin'].includes(user?.role);
export function subscription(user){
 if(!user)return null;
 const s=one('SELECT s.*,p.title FROM subscriptions s JOIN plans p ON p.id=s.plan_id WHERE user_id=?',user.id);
 return s?{...s,state:s.status==='revoked'?'revoked':s.starts_at>Date.now()?'scheduled':s.ends_at<=Date.now()?'expired':'active'}:null;
}
export const canRead=(m,user)=>m?.accessLevel!=='subscriber'||staff(user)||subscription(user)?.state==='active';
export function preview(m,user){if(canRead(m,user))return m;return {id:m.id,title:m.title,code:m.code,profession:m.profession,kind:m.kind,status:m.status,accessLevel:'subscriber',locked:true,steps:[],attachments:[],blocks:[]};}
export function registerAccounts(app,{auth,admin}){
 app.get('/api/plans',(req,res)=>res.json({plans:all('SELECT * FROM plans WHERE enabled=1'),paymentMode:'manual',checkoutAvailable:false}));
 app.get('/api/account',auth,(req,res)=>res.json({subscription:subscription(req.user),requests:all('SELECT * FROM access_requests WHERE user_id=? ORDER BY created_at DESC',req.user.id),privacyRequests:all('SELECT * FROM privacy_requests WHERE user_id=? ORDER BY created_at DESC',req.user.id)}));
 app.post('/api/account/access-request',auth,(req,res)=>{const p=one('SELECT * FROM plans WHERE id=? AND enabled=1',String(req.body.planId||''));if(!p)return fail(res,400,'Выберите доступный план');if(one("SELECT id FROM access_requests WHERE user_id=? AND status='pending'",req.user.id))return fail(res,409,'Заявка уже ожидает решения');const id=randomUUID();run('INSERT INTO access_requests VALUES(?,?,?,?,?)',id,req.user.id,p.id,'pending',Date.now());audit(req.user.id,'access.requested',id);res.status(201).json({id});});
 app.post('/api/account/access-request/:id/cancel',auth,(req,res)=>{const r=run("UPDATE access_requests SET status='cancelled' WHERE id=? AND user_id=? AND status='pending'",req.params.id,req.user.id);if(!r.changes)return fail(res,409,'Заявка уже обработана или недоступна');audit(req.user.id,'access.cancelled',req.params.id);res.json({ok:true});});
 app.post('/api/account/password',auth,(req,res)=>{const {currentPassword,password}=req.body;if(!text(currentPassword,200)||!text(password,200)||password.length<12)return fail(res,400,'Нужен текущий пароль и новый пароль от 12 до 200 символов');const u=one('SELECT * FROM users WHERE id=?',req.user.id);if(!timingSafeEqual(scryptSync(currentPassword,u.salt,64),Buffer.from(u.hash,'hex')))return fail(res,403,'Текущий пароль неверен');const salt=randomBytes(16).toString('hex');db.exec('BEGIN');try{run('UPDATE users SET salt=?,hash=? WHERE id=?',salt,scryptSync(password,salt,64).toString('hex'),u.id);run('DELETE FROM sessions WHERE user_id=? AND token<>?',u.id,req.session.token);audit(u.id,'password.changed',u.id);db.exec('COMMIT')}catch(e){db.exec('ROLLBACK');throw e}res.json({ok:true});});
 app.get('/api/account/export',auth,(req,res)=>{const u=req.user.id;res.set('Content-Disposition','attachment; filename="navigator-personal-data.json"');audit(u,'data.exported',u);res.json({exportedAt:new Date().toISOString(),user:req.user,personal:all('SELECT kind,item,data FROM personal WHERE user_id=?',u).map(r=>({...r,data:JSON.parse(r.data)})),notifications:all('SELECT id,data,read FROM notifications WHERE user_id=?',u).map(r=>({...r,data:JSON.parse(r.data)})),subscription:subscription(req.user),audit:all('SELECT action,created_at,details FROM account_audit WHERE actor_id=? OR target_id=? OR target_id IN (SELECT id FROM access_requests WHERE user_id=?) OR target_id IN (SELECT id FROM privacy_requests WHERE user_id=?)',u,u,u,u).map(r=>({...r,details:JSON.parse(r.details)})),requests:all('SELECT * FROM access_requests WHERE user_id=?',u),legalQuestions:all('SELECT * FROM legal_questions WHERE user_id=?',u).map(visibleQuestion),privacyRequests:all('SELECT * FROM privacy_requests WHERE user_id=?',u)});});
 app.post('/api/account/privacy-request',auth,(req,res)=>{const {kind,message=''}=req.body;if(!['access','correction','deletion'].includes(kind)||typeof message!=='string'||message.length>3000)return fail(res,400,'Проверьте тип и текст обращения');if(one("SELECT id FROM privacy_requests WHERE user_id=? AND kind=? AND status='pending'",req.user.id,kind))return fail(res,409,'Такое обращение уже открыто');const id=randomUUID();run('INSERT INTO privacy_requests(id,user_id,kind,message,created_at) VALUES(?,?,?,?,?)',id,req.user.id,kind,message,Date.now());audit(req.user.id,'privacy.requested',id,{kind});res.status(201).json({id});});
 app.get('/api/privacy',(req,res)=>{const settings={...operatorDefaults,...JSON.parse(one('SELECT data FROM operator_settings WHERE id=1')?.data||'{}')};res.json({operator:settings,configured:!!(settings.name&&settings.address),version:'2026-09-21',data:['Логин и хэш пароля','Избранное, задачи и прогресс','Подписка, обращения и правовые вопросы с ответами редакторов','Сессии и журнал действий'],tracking:false,payments:false});});
 app.post('/api/admin/accounts',admin,(req,res)=>{const username=req.body.username;if(typeof username!=='string'||!/^[a-zA-Z0-9_.-]{3,60}$/.test(username))return fail(res,400,'Логин: 3–60 латинских букв, цифр, точек, дефисов или подчёркиваний');if(one('SELECT id FROM users WHERE username=?',username))return fail(res,409,'Логин уже занят');const id=randomUUID(),password=randomBytes(18).toString('base64url'),salt=randomBytes(16).toString('hex');run('INSERT INTO users VALUES(?,?,?,?,?)',id,username,'reader',salt,scryptSync(password,salt,64).toString('hex'));audit(req.user.id,'account.created',id);res.status(201).json({id,username,password});});
 app.get('/api/admin/accounts',admin,(req,res)=>res.json({users:all('SELECT id,username,role FROM users').map(u=>({...u,subscription:subscription(u)})),plans:all('SELECT * FROM plans'),requests:all('SELECT r.*,u.username,p.title FROM access_requests r JOIN users u ON u.id=r.user_id JOIN plans p ON p.id=r.plan_id ORDER BY created_at DESC LIMIT 200'),privacyRequests:all('SELECT r.*,u.username FROM privacy_requests r JOIN users u ON u.id=r.user_id ORDER BY created_at DESC LIMIT 200'),audit:all('SELECT * FROM account_audit ORDER BY id DESC LIMIT 100')}));
 app.put('/api/admin/plans/:id',admin,(req,res)=>{const {title,durationDays,description='',enabled=true}=req.body;if(!/^[a-z0-9-]{1,50}$/.test(req.params.id)||!text(title,150)||!Number.isInteger(durationDays)||durationDays<1||durationDays>3660||typeof description!=='string'||description.length>1500||typeof enabled!=='boolean')return fail(res,400,'Проверьте название, срок и описание плана');run('INSERT INTO plans VALUES(?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET title=excluded.title,duration_days=excluded.duration_days,description=excluded.description,enabled=excluded.enabled',req.params.id,title.trim(),durationDays,description,Number(enabled));audit(req.user.id,'plan.updated',req.params.id);res.json({ok:true});});
 app.post('/api/admin/subscriptions/:userId',admin,(req,res)=>{const user=one('SELECT id FROM users WHERE id=?',req.params.userId),p=one('SELECT * FROM plans WHERE id=? AND enabled=1',String(req.body.planId||''));if(!user||!p||!text(req.body.reason,1000))return fail(res,400,'Нужны пользователь, план и основание');const current=subscription(user),now=Date.now(),ends=Math.max(now,current?.state==='active'?current.ends_at:0)+p.duration_days*86400000;db.exec('BEGIN');try{run("INSERT INTO subscriptions VALUES(?,?,?,?,?,?,?) ON CONFLICT(user_id) DO UPDATE SET plan_id=excluded.plan_id,starts_at=excluded.starts_at,ends_at=excluded.ends_at,status='active',reason=excluded.reason,updated_at=excluded.updated_at",user.id,p.id,now,ends,'active',req.body.reason,now);run("UPDATE access_requests SET status='approved' WHERE user_id=? AND status='pending'",user.id);audit(req.user.id,'subscription.granted',user.id,{planId:p.id,endsAt:ends,reason:req.body.reason});db.exec('COMMIT')}catch(e){db.exec('ROLLBACK');throw e}res.json(subscription(user));});
 app.post('/api/admin/subscriptions/:userId/revoke',admin,(req,res)=>{if(!text(req.body.reason,1000))return fail(res,400,'Укажите основание отзыва');const r=run("UPDATE subscriptions SET status='revoked',reason=?,updated_at=? WHERE user_id=? AND status='active'",req.body.reason,Date.now(),req.params.userId);if(!r.changes)return fail(res,409,'Нет действующего доступа');audit(req.user.id,'subscription.revoked',req.params.userId,{reason:req.body.reason});res.json({ok:true});});
 app.post('/api/admin/access-requests/:id/reject',admin,(req,res)=>{if(!text(req.body.reason,1000))return fail(res,400,'Укажите причину');const r=run("UPDATE access_requests SET status='rejected' WHERE id=? AND status='pending'",req.params.id);if(!r.changes)return fail(res,409,'Заявка уже обработана');audit(req.user.id,'access.rejected',req.params.id,{reason:req.body.reason});res.json({ok:true});});
 app.post('/api/admin/privacy-requests/:id/resolve',admin,(req,res)=>{const r=one("SELECT * FROM privacy_requests WHERE id=? AND status='pending'",req.params.id);if(!r)return fail(res,409,'Обращение уже обработано');if(!text(req.body.response,3000))return fail(res,400,'Введите ответ пользователю');if(r.kind==='deletion'&&req.body.deleteAccount===true){const u=one('SELECT * FROM users WHERE id=?',r.user_id);if(u.role!=='reader'||u.id===req.user.id)return fail(res,400,'Удаление служебной учётной записи требует отдельной процедуры');if(req.body.confirmation!==u.username)return fail(res,400,'Введите логин удаляемого пользователя');db.exec('BEGIN');try{for(const request of [...all('SELECT id FROM access_requests WHERE user_id=?',u.id),...all('SELECT id FROM privacy_requests WHERE user_id=?',u.id)])run('DELETE FROM account_audit WHERE target_id=?',request.id);for(const table of ['legal_questions','personal','notifications','sessions','subscriptions','access_requests','privacy_requests'])run(`DELETE FROM ${table} WHERE user_id=?`,u.id);run('DELETE FROM account_audit WHERE actor_id=? OR target_id=?',u.id,u.id);run('DELETE FROM users WHERE id=?',u.id);audit(req.user.id,'account.deleted','removed',{requestKind:'deletion'});db.exec('COMMIT')}catch(e){db.exec('ROLLBACK');throw e}return res.json({ok:true,deleted:true});}run("UPDATE privacy_requests SET status='resolved',response=?,resolved_at=? WHERE id=?",req.body.response,Date.now(),r.id);audit(req.user.id,'privacy.resolved',r.id,{kind:r.kind});res.json({ok:true});});
 app.put('/api/admin/operator',admin,(req,res)=>{const {name,address,email='',hosting='',retention=''}=req.body;if(!text(name,300)||!text(address,1000)||typeof email!=='string'||email.length>200||(email&&!/^\S+@\S+\.\S+$/.test(email))||typeof hosting!=='string'||hosting.length>1000||typeof retention!=='string'||retention.length>3000)return fail(res,400,'Заполните наименование, адрес и корректный email, если он указан');const data={name:name.trim(),address:address.trim(),email:email.trim(),hosting,retention};run('INSERT INTO operator_settings VALUES(1,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data',JSON.stringify(data));audit(req.user.id,'operator.updated','operator');res.json(data);});
}
