import {parseChanges,validInstant} from './changes-schema.js';
export const UPSTREAM='https://bogolubov-creator.github.io/club-pravo-hse-mirror/data/changes.json';
export const PUBLISHED='https://bogolubov-creator.github.io/profession-navigator/changes.json';
export const textOf=item=>[item.title,item.summary,...item.blocks.map(b=>b.segments.map(s=>s.text).join(''))].join('\n');
const rules={hr:/трудов|работодател|работник|миграц|кадров|сверхуроч|зарплат/i,'general-director':/организац|юридическ|компани|предприяти|управлен|бизнес|контрол/i,procurement:/закуп|постав|контракт|казначей|снабж/i,'product-management':/потребител|маркетплейс|персональн|подписк|реклам|цифров|интернет/i,creative:/авторск|товарн.{0,10}знак|интеллектуальн|произведен|дизайн/i,'software-development':/программ|нейросет|искусственн.{0,10}интеллект|домен|информационн|кибер|персональн/i,medicine:/медицин|здравоохран|лекарств|врач|пациент/i,'real-estate':/недвижим|жил.{0,8}дом|застрой|строитель|земель|жилищ/i,logistics:/перевоз|транспорт|экспедитор|логист|топлив|экспорт|вывоз|таможен/i,nonprofit:/некоммерческ|благотвор|пожертв|волонт|грант|субсиди/i,startup:/предприним|самозанят|налог|инвестиц|стартап|крипто|цифров/i,'occupational-safety':/охран.{0,5}труда|промышленн.{0,5}безопас|опасн.{0,8}объект|несчастн|производствен/i,education:/образован|педагог|школ|учител|кадет|обучен/i,'journalism-ip':/журналист|средств.{0,10}информац|авторск|фотограф|изображен|реклам|публикац/i};
export const routeProfessions=item=>Object.entries(rules).filter(([,rule])=>rule.test(textOf(item))).map(([id])=>id);
export function brief(item){
 if(item.entryType==='act')return {what:[],dates:[],actions:[]};
 const result={what:[],dates:[],actions:[]};let section='what';
 for(const b of item.blocks){const text=b.segments.map(s=>s.text).join('');if(b.heading){section=/с какой даты|срок|когда/i.test(text)?'dates':/что делать|действия/i.test(text)?'actions':/что меняется|ключевое/i.test(text)?'what':'other';continue;}if(section!=='other')result[section].push(text);}
 if(!result.what.length&&item.summary)result.what=[item.summary];
 return result;
}
export function selectChanges(items,params){const q=(params.get('q')||'').toLowerCase().replaceAll('ё','е'),view=params.get('view')||'digest',profession=params.get('profession');return items.filter(i=>(view==='all'||i.entryType===view)&&(!profession||routeProfessions(i).includes(profession))&&(!q||textOf(i).toLowerCase().replaceAll('ё','е').includes(q))&&(!params.get('topic')||i.topic===params.get('topic'))&&(!params.get('from')||i.published>=params.get('from'))&&(!params.get('to')||i.published<=params.get('to'))).sort((a,b)=>(a.published.localeCompare(b.published)||a.id.localeCompare(b.id))*(params.get('sort')==='oldest'?1:-1));}
export function parseSnapshot(raw){const data=parseChanges(raw);return {...data,navigatorSync:raw.navigatorSync&&typeof raw.navigatorSync==='object'?{checkedAt:validInstant(raw.navigatorSync.checkedAt)?raw.navigatorSync.checkedAt:null,receivedAt:validInstant(raw.navigatorSync.receivedAt)?raw.navigatorSync.receivedAt:null,status:['ok','unavailable'].includes(raw.navigatorSync.status)?raw.navigatorSync.status:'unavailable'}:{checkedAt:null,receivedAt:null,status:'unavailable'}};}
