import {chromium,webkit} from '@playwright/test';import AxeBuilder from '@axe-core/playwright';import fs from 'node:fs';
const base=process.env.QA_URL||'http://127.0.0.1:4317',mirror=!!process.env.QA_URL, credentials=JSON.parse(fs.readFileSync('private/credentials.json'));
const report={base,checks:[],errors:[],axe:[]};
const browser=await chromium.launch({headless:true,...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{})});const context=await browser.newContext({viewport:{width:1440,height:1000}});const page=await context.newPage();page.on('pageerror',e=>report.errors.push(e.message));
const check=(label,ok)=>{if(!ok)throw Error(label);report.checks.push(label)};
async function login(name){await page.goto(base+'/#/login');const c=credentials.find(c=>c.username===name);await page.getByLabel('Логин',{exact:true}).fill(c.username);await page.getByLabel('Пароль',{exact:true}).fill(c.password);await page.getByRole('button',{name:'Войти',exact:true}).last().click();await page.getByRole('button',{name:new RegExp(name+' · Выйти')}).waitFor();}
try{
 await page.goto(base);await page.getByRole('heading',{name:'Разобраться. Действовать.'}).waitFor();await page.getByRole('button',{name:/Генеральный директор/}).waitFor();await page.screenshot({path:'work/desktop.png',fullPage:true});
 check('Каталог 14 направлений',await page.locator('.profession-grid button').count()===14);
 await page.getByRole('textbox',{name:'Поиск по ситуации'}).fill('GD-A-01');await page.getByRole('button',{name:'Найти',exact:false}).click();await page.locator('.material-row').first().waitFor();await page.locator('.material-row').filter({has:page.getByText('GD-A-01',{exact:true})}).first().click();await page.getByRole('button',{name:'Пройти по шагам'}).click();await page.locator('.active-step').waitFor();await page.reload();await page.locator('.active-step').waitFor();check('Поиск, карточка, шаг и прямая ссылка после перезагрузки',true);
 await page.screenshot({path:'work/instruction.png',fullPage:true});
 const pdf=await page.request.get(base+(mirror?'/files/SRC-039.pdf':'/files/SRC-039'));check('PDF формы доступен',pdf.status()===200&&(await pdf.body()).subarray(0,4).toString()==='%PDF');
 if(!mirror){
 await login('reader');await page.goto(base+'/#/item/SRC-015-LOG-A-01?step=0');await page.locator('.active-step').waitFor();if(await page.getByRole('button',{name:'Отметить выполненным',exact:true}).count())await page.getByRole('button',{name:'Отметить выполненным',exact:true}).click();await page.getByRole('button',{name:'Шаг выполнен · отменить'}).waitFor();await page.reload();await page.getByRole('button',{name:'Шаг выполнен · отменить'}).waitFor();check('Отметка шага сохраняется через браузер',true);
 if(await page.getByRole('button',{name:'В избранное',exact:true}).count())await page.getByRole('button',{name:'В избранное',exact:true}).click();await page.getByRole('button',{name:'Убрать из избранного'}).waitFor();await page.goto(base+'/#/plan');await page.getByLabel('Задача',{exact:true}).fill('Браузерная проверка');await page.getByLabel('Мой срок').fill('2026-09-22');await page.getByRole('button',{name:'Добавить',exact:true}).click();await page.getByText('Браузерная проверка',{exact:true}).first().waitFor();check('Задача добавляется в личный план',true);
 await page.getByRole('button',{name:'reader · Выйти'}).click();await page.getByRole('button',{name:'Войти',exact:true}).waitFor();await login('editor');await page.goto(base+'/#/admin?kind=task&profession=journalism-ip');await page.locator('.admin-row').first().waitFor();check('Журналистика: 16 редакционных заданий',await page.locator('.admin-row').count()===16);
 await page.goto(base+'/#/admin/edit/SRC-002-GD-A-01');await page.getByLabel('Название',{exact:true}).waitFor();const title=await page.getByLabel('Название',{exact:true}).inputValue();await page.getByLabel('Название',{exact:true}).fill(title+' · проверка UI');await page.getByRole('button',{name:'Сохранить',exact:true}).first().click();await page.getByRole('status').filter({hasText:'сохранена'}).waitFor();await page.reload();await page.getByLabel('Название',{exact:true}).waitFor();check('Редактор сохраняет и повторно открывает запись',(await page.getByLabel('Название',{exact:true}).inputValue()).endsWith('проверка UI'));await page.getByLabel('Название',{exact:true}).fill(title);await page.getByRole('button',{name:'Сохранить',exact:true}).first().click();await page.getByRole('status').filter({hasText:'сохранена'}).waitFor();await page.screenshot({path:'work/admin.png',fullPage:false});
 }
 await page.goto(base+'/#/home');await page.getByRole('heading',{name:'Разобраться. Действовать.'}).waitFor();for(const width of [320,390,768,1024,1440]){await page.setViewportSize({width,height:900});await page.waitForTimeout(100);check('Нет горизонтального переполнения '+width,await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));if(width===390)await page.screenshot({path:'work/mobile.png',fullPage:true});}
 report.axe=(await new AxeBuilder({page}).analyze()).violations.map(v=>({id:v.id,impact:v.impact,count:v.nodes.length}));await page.keyboard.press('Tab');check('Клавиатурный фокус доступен',await page.evaluate(()=>document.activeElement!==document.body));
}catch(e){report.errors.push(e.stack)}finally{await browser.close();fs.writeFileSync('work/browser-qa'+(mirror?'-mirror':'')+'.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));if(report.errors.length)process.exitCode=1;}
