import {execFileSync} from 'node:child_process';
import fs from 'node:fs';import path from 'node:path';import {createHash} from 'node:crypto';import {db,all,one,run,unpack,privateDir} from '../server/db.js';
const sources=new Map(fs.readFileSync(path.join(privateDir,'handoff/inventory/content_sources.jsonl'),'utf8').trim().split('\n').map(JSON.parse).map(x=>[x.source_id,x.blocks]));
const clean=s=>s.replace(/\u2014/g,'–').replace(/\u200b/g,'').replace(/\r/g,'').trim();
const compact=s=>clean(s).replace(/\n\s*\d{1,3}\s*\n/g,'\n').replace(/[ \t]+/g,' ').replace(/\n(?!\s*\d+[.)])/g,' ').trim();
function store(m){const old=one('SELECT * FROM materials WHERE id=?',m.id);if(old&&old.revision>1&&one('SELECT actor FROM versions WHERE material_id=? ORDER BY revision DESC LIMIT 1',m.id)?.actor!=='content-expansion')return false;const comparable={...m};if(old){const before=JSON.parse(old.data);delete before.revision;if(JSON.stringify(before)===JSON.stringify(comparable))return false;}m.revision=(old?.revision||0)+1;run('INSERT INTO materials VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET code=excluded.code,profession=excluded.profession,kind=excluded.kind,status=excluded.status,revision=excluded.revision,data=excluded.data',m.id,m.sourceId||null,m.code||'',m.profession,m.kind,m.status,m.revision,JSON.stringify(m));run('INSERT INTO versions(material_id,revision,actor,created,data) VALUES(?,?,?,?,?)',m.id,m.revision,'content-expansion',new Date().toISOString(),JSON.stringify(m));return true;}
const fields={'Ситуация':'situation','Кому адресовано':'audience','Кому':'audience','Срочность':'urgency','Шаги':'stepsRaw','Что подготовить':'documents','Чего не делать':'errors','Правовое основание':'norms','Правовые основания':'norms','Дата сверки норм':'sourceDate','Связанные вопросы гида':'relatedQuestions','Связанные вопросы':'relatedQuestions','Приложения':'appendices'};
const pedSteps=JSON.parse(execFileSync('uv',['run','--no-project','python','scripts/docx-steps.py',path.join(privateDir,'handoff/materials/13_Педагог/Материалы/Педагоги_карточки.docx')],{encoding:'utf8'}));
const report={updated:[],issues:[]};db.exec('BEGIN');try{
for(const [sid,prefix,profession]of[['SRC-008','MED','medicine'],['SRC-026','SOT','occupational-safety'],['SRC-031','PED','education']]){
 const source=JSON.parse(one('SELECT data FROM sources WHERE id=?',sid).data);const body=clean(sources.get(sid).map(b=>b.text||'').join('\n'));const re=prefix==='PED'?/^ID карточки:\s*(PED-A-\d{2})\s*(.*)$/gm:new RegExp('^('+prefix+'-A-\\d{2})[.\\s]+(.*)$','gm');const starts=[...body.matchAll(re)];
 for(let i=0;i<starts.length;i++){const hit=starts[i],code=hit[1],chunk=body.slice(hit.index,starts[i+1]?.index??body.length).replace(/\n\s*(?:PED|MED|SOT)-A-\d{2}\s*$/,'');const lines=chunk.split('\n');const parts={};let mode='title';parts.title=hit[2];
 for(const raw of lines.slice(1)){const t=clean(raw);if(!t||/^\d{1,3}$/.test(t))continue;const k=Object.keys(fields).find(k=>t===k||t.startsWith(k+':'));if(k&&!(mode==='stepsRaw'&&fields[k]==='norms'&&t.slice(k.length).replace(/^:\s*/,'').trim())){mode=fields[k];parts[mode]=(parts[mode]||'')+'\n'+t.slice(k.length).replace(/^:\s*/,'')}else parts[mode]=(parts[mode]||'')+'\n'+t;}
 let pieces;if(/^\s*\d+[.)]/.test(parts.stepsRaw||''))pieces=parts.stepsRaw.split(/\n(?=\s*\d{1,2}[.)](?:\s|$))/);else pieces=(parts.stepsRaw||'').split('\n');if(prefix==='PED')pieces=pedSteps[code]||pieces;pieces=pieces.map(compact).filter(Boolean);
 const steps=pieces.map((text,j)=>({id:'step-'+createHash('sha256').update(code+'|'+text).digest('hex').slice(0,12),text,attachments:[],branches:[]}));if(!steps.length||steps.some(s=>s.text.length<15)){report.issues.push({code,reason:'Некорректное выделение шагов'});continue;}
 for(const s of steps)s.branches=[...s.text.matchAll(/(?:шагу|шаг)\s+(\d+)/gi)].map(x=>({label:'К шагу '+x[1],index:Number(x[1])-1})).filter(b=>b.index>=0&&b.index<steps.length);
 const m={id:sid+'-'+code,sourceId:sid,sourceName:path.basename(source.path),sourceSha:source.sha256,profession,code,kind:'card',status:'published',legalStatus:'unverified',contentOrigin:'source',title:compact(parts.title),steps,attachments:[],blocks:[{type:'text',locator:'code/'+code,text:clean(chunk)}],tags:[],...Object.fromEntries(Object.entries(parts).filter(([k])=>!['title','stepsRaw'].includes(k)).map(([k,v])=>[k,compact(v)]))};
 m.externalLinks=[...new Set((parts.appendices||'').match(/https?:\/\/[^\s)]+/g)||[])].map(url=>({url,label:'Приложение из источника',checked:false}));
 if(store(m))report.updated.push(code);
 }
}
for(const row of all("SELECT * FROM materials WHERE source_id='SRC-035' AND kind='question'")){if(row.revision>1)continue;const m=unpack(row);m.status='published';m.contentOrigin='source';if(!m.simple){m.simple='HR-специалист организует работу с персоналом: участвует в подборе сотрудников и развитии кадровых процессов организации. Конкретные обязанности определяются его трудовой функцией.';m.contentOrigin='edited-source'}if(JSON.stringify(m.blocks).includes('хз как заменить'))throw Error('Авторская пометка в публичном фрагменте');if(store(m))report.updated.push(m.id);}
// Новые памятки не подменяют исходные задания: у них собственное происхождение и отдельные записи.
const authored=JSON.parse(fs.readFileSync('content/editorial-cards.json','utf8'));
for(const m of authored){const data={...m,id:'editorial-'+m.code,kind:'card',status:'published',legalStatus:'unverified',contentOrigin:'editorial',sourceName:'Редакционная памятка от 21.09.2026',attachments:[],tags:[],blocks:[],steps:m.steps.map((text,i)=>({id:m.code+'-step-'+(i+1),text,attachments:[],branches:[]}))};if(store(data))report.updated.push(data.code);}
for(const p of all('SELECT * FROM professions')){const data=JSON.parse(p.data);const counts=all("SELECT kind,count(*) n FROM materials WHERE profession=? AND status='published' GROUP BY kind",p.id);data.note=counts.map(x=>({card:'Карточки',question:'Вопросы',form:'Документы',service:'Сервисы',guide:'Фрагменты гида'})[x.kind]+': '+x.n).join(' · ')+'. Правовая актуальность требует сверки.';data.coverageNote=['procurement','product-management','software-development'].includes(p.id)?'Исходный гид не найден. Доступны новые редакционные памятки.':p.id==='journalism-ip'?'Исходное задание и учебный пример сохранены отдельно. Опубликованы новые редакционные памятки по 16 темам.':'Исходные задания и альтернативные версии доступны редактору.';run('UPDATE professions SET data=? WHERE id=?',JSON.stringify(data),p.id);}
db.exec('COMMIT');fs.writeFileSync('work/content-expansion.json',JSON.stringify(report,null,2));console.log(JSON.stringify({updated:report.updated.length,issues:report.issues}));}catch(e){db.exec('ROLLBACK');throw e}
