import fs from 'node:fs/promises';import path from 'node:path';import {pathToFileURL} from 'node:url';
import {UPSTREAM,PUBLISHED,parseSnapshot} from '../shared/changes.js';
import {parseChanges,validInstant} from '../shared/changes-schema.js';
export async function fetchSnapshot(url){const r=await fetch(url,{signal:AbortSignal.timeout(20000),redirect:'error'});if(!r.ok)throw Error('source_http_'+r.status);const reader=r.body.getReader(),chunks=[];let total=0;while(true){const {done,value}=await reader.read();if(done)break;total+=value.length;if(total>8000000){await reader.cancel();throw Error('source_too_large')}chunks.push(value)}return JSON.parse(Buffer.concat(chunks).toString('utf8'));}
export async function synchronize(previous,now,get=fetchSnapshot){
 try{if(!validInstant(now))throw Error('invalid_clock');const incoming=parseChanges(await get(UPSTREAM));if(!incoming.items.length)throw Error('empty_source');if(incoming.lastPostAt&&Date.parse(incoming.lastPostAt)>Date.parse(now)+300000)throw Error('future_source');if(previous.lastPostAt&&(!incoming.lastPostAt||incoming.lastPostAt<previous.lastPostAt))throw Error('source_went_backwards');const items=new Map(previous.items.map(i=>[i.id,i]));for(const item of incoming.items)items.set(item.id,item);const dates=[...items.values()].map(i=>i.published).sort();return {...parseChanges({...incoming,periodFrom:dates[0],periodTo:dates.at(-1),items:[...items.values()]}),navigatorSync:{checkedAt:now,receivedAt:now,status:'ok'}};
 }catch{return {...previous,navigatorSync:{...previous.navigatorSync,checkedAt:now,status:'unavailable'}}}
}
export async function syncFile(output,{previousPublished=false}={}){let previous=parseSnapshot(JSON.parse(await fs.readFile(output,'utf8')));if(previousPublished){try{previous=parseSnapshot(await fetchSnapshot(PUBLISHED))}catch(e){if(e.message!=='source_http_404')throw e;}}
 const result=await synchronize(previous,new Date().toISOString());const tmp=output+'.tmp';await fs.mkdir(path.dirname(output),{recursive:true});await fs.writeFile(tmp,JSON.stringify(result,null,2)+'\n');await fs.rename(tmp,output);return result;}
if(process.argv[1]&&import.meta.url===pathToFileURL(path.resolve(process.argv[1])).href){const output=path.resolve('public/release/changes.json');const result=await syncFile(output,{previousPublished:process.argv.includes('--previous-published')});console.log(JSON.stringify({status:result.navigatorSync.status,lastPostAt:result.lastPostAt,items:result.items.length}));if(result.navigatorSync.status!=='ok')console.log('::warning::Лента недоступна; сохранён предыдущий выпуск');}
