import React,{useEffect,useState} from 'react';
import {api,labels,fileUrl,mirror} from './api';
import {Blocks} from './reader';
import {remapSteps} from '../shared/steps';
import {AccountsAdmin} from './account';
import {Pencil,Copy,Eye} from 'lucide-react';
const sections=[['materials','Материалы'],['sources','Источники и импорт'],['stats','Статистика'],['taxonomy','Категории и чек-листы'],['professions','Профессии'],['users','Права доступа'],['accounts','Подписки и данные']];
export function Admin({route,user,notify,catalog}){
 const tab=route.params.get('tab')||'materials',id=route.path.startsWith('admin/edit/')?route.path.slice(11):null;
 if(mirror||!['admin','editor'].includes(user?.role))return <div className="empty"><h1>Редакторский кабинет</h1><p>Для доступа войдите с учётной записью редактора или администратора.</p><a href="#/login">Войти</a></div>;
 return <><h1>{id?"Редактирование материала":"Администрирование"}</h1><div className="tabs">{sections.filter(([k])=>!['users','accounts'].includes(k)||user.role==='admin').map(([k,l])=><a className={tab===k&&!id?'selected':''} href={'#/admin?tab='+k} key={k}>{l}</a>)}</div>{id?<Editor id={id} notify={notify} catalog={catalog}/>:tab==='materials'?<AdminList route={route} notify={notify} catalog={catalog}/>:tab==='sources'?<Sources notify={notify} user={user}/>:tab==='stats'?<Stats/>:tab==='taxonomy'?<Taxonomy notify={notify}/>:tab==='accounts'?<AccountsAdmin notify={notify}/>:tab==='professions'?<Professions catalog={catalog} notify={notify}/>:<Users notify={notify}/>}</>;
}
function AdminList({route,notify,catalog}){
 const [data,setData]=useState({items:[],total:0});const p=route.params;useEffect(()=>{api('/api/materials?'+new URLSearchParams({...Object.fromEntries(p),admin:1,limit:30})).then(setData).catch(e=>notify(e.message))},[p.toString()]);
 const filter=(k,v)=>{const n=new URLSearchParams(p);n.set(k,v);if(k!=='page')n.set('page',1);location.hash='/admin?'+n;};
 return <><div className="filters"><label>Поиск<input value={p.get('q')||''} onChange={e=>filter('q',e.target.value)} placeholder="Название, код, текст"/></label><label>Тип<select value={p.get('kind')||''} onChange={e=>filter('kind',e.target.value)}><option value="">Все типы</option>{['card','question','guide','form','service','norm','task','example'].map(k=><option key={k} value={k}>{labels[k]}</option>)}</select></label><label>Статус<select value={p.get('status')||''} onChange={e=>filter('status',e.target.value)}><option value="">Все статусы</option>{['draft','review','ready','published','archived'].map(k=><option key={k} value={k}>{labels[k]}</option>)}</select></label><label>Профессия<select value={p.get('profession')||''} onChange={e=>filter('profession',e.target.value)}><option value="">Все направления</option>{catalog.map(x=><option key={x.id} value={x.id}>{x.title}</option>)}</select></label><label>Порядок<select value={p.get('sort')||'asc'} onChange={e=>filter('sort',e.target.value)}><option value="asc">А–Я</option><option value="desc">Я–А</option></select></label><button className="primary" onClick={async()=>{try{const m=await api('/api/admin/materials',{method:'POST',body:{}});location.hash='/admin/edit/'+m.id}catch(e){notify(e.message)}}}>Создать материал</button></div><p>{data.total} записей</p><div className="table-scroll"><table className="admin-table"><thead><tr><th>Название</th><th>Категория / этап</th><th>Профессия</th><th>Статус</th><th>Действия</th></tr></thead><tbody>{data.items.map(m=><tr key={m.id}><td><a href={'#/admin/edit/'+m.id}>{m.title}</a><small>{m.code} · {labels[m.kind]}</small></td><td>{m.category||'Не задана'}<small>{m.stage||'Этап не задан'}</small></td><td>{catalog.find(p=>p.id===m.profession)?.title||'Общие материалы'}</td><td><span className="pill">{labels[m.status]}</span></td><td><div className="row-actions"><a aria-label={'Редактировать: '+m.title} href={'#/admin/edit/'+m.id}><Pencil size={18}/></a><button aria-label={'Копировать: '+m.title} onClick={async()=>{try{const full=await api('/api/materials/'+m.id);const copy=await api('/api/admin/materials',{method:'POST',body:{...full,title:full.title+' (копия)',code:'',status:'draft'}});location.hash='/admin/edit/'+copy.id}catch(e){notify(e.message)}}}><Copy size={18}/></button><a aria-label={'Просмотреть: '+m.title} href={'#/item/'+m.id}><Eye size={18}/></a>{m.kind==='card'&&<a className="steps-link" href={'#/item/'+m.id+'?step=0'}>Шаги инструкции</a>}</div></td></tr>)}</tbody></table></div><div className="pagination"><button disabled={!(Number(p.get('page'))>1)} onClick={()=>filter('page',(Number(p.get('page'))||1)-1)}>Назад</button><span>Страница {p.get('page')||1}</span><button disabled={(Number(p.get('page'))||1)*30>=data.total} onClick={()=>filter('page',(Number(p.get('page'))||1)+1)}>Далее</button></div></>;
}
function Editor({id,notify,catalog}){
 const [m,set]=useState(null),[versions,setVersions]=useState([]),[original,setOriginal]=useState(null),[compare,setCompare]=useState(null);const load=()=>{api('/api/materials/'+id).then(set);api('/api/admin/versions/'+id).then(setVersions)};
 useEffect(load,[id]);if(!m)return <p>Загрузка…</p>;const field=(k,v)=>set({...m,[k]:v});
 const save=async()=>{try{const saved=await api('/api/admin/materials/'+id,{method:'PUT',body:m});set(saved);api('/api/admin/versions/'+id).then(setVersions);notify('Версия '+saved.revision+' сохранена')}catch(e){notify(e.message)}};
 return <><div className="editor-actions"><button className="primary" onClick={save}>Сохранить</button><a href={'#/item/'+id}>Предпросмотр</a><button onClick={async()=>{try{const copy=await api('/api/admin/materials',{method:'POST',body:{...m,title:m.title+' (копия)',code:'',status:'draft'}});location.hash='/admin/edit/'+copy.id}catch(e){notify(e.message)}}}>Копировать</button><span>Версия {m.revision}</span></div><div className="panel editor-form"><label>Название<input value={m.title} onChange={e=>field('title',e.target.value)}/></label><div className="form-grid"><label>Тип<select value={m.kind} onChange={e=>field('kind',e.target.value)}>{['card','question','guide','form','service','norm','task','example'].map(k=><option key={k} value={k}>{labels[k]}</option>)}</select></label><label>Статус<select aria-label="Статус" value={m.status} onChange={e=>field('status',e.target.value)}>{['draft','review','ready','published','archived'].map(k=><option key={k} value={k}>{labels[k]}</option>)}</select></label><label>Профессия<select aria-label="Профессия" value={m.profession} onChange={e=>field('profession',e.target.value)}><option value="">Общие материалы</option>{catalog.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select></label><label>Доступ<select value={m.accessLevel||'public'} onChange={e=>field('accessLevel',e.target.value)}><option value="public">Открытый</option><option value="subscriber">По подписке</option></select><small>Ранее опубликованные открытые версии могут сохраняться у читателей и в публичном зеркале.</small></label><label>Исходный код<input value={m.code||''} onChange={e=>field('code',e.target.value)}/></label></div>
 {['situation','audience','side','scope','urgency','deadlines','legal','simple','documents','errors','norms','editorNote'].map((k,i)=><label key={k}>{['Ситуация','Адресат','Сторона','Границы применения','Срочность','Сроки по источнику','Юридически точно','Простыми словами','Что подготовить','Чего не делать','Основания','Заметка редактору'][i]}<textarea rows={k==='legal'||k==='simple'?6:2} value={m[k]||''} onChange={e=>field(k,e.target.value)}/></label>)}
 <div className="form-grid">{['category','stage','url'].map((k,i)=><label key={k}>{['Категория','Этап','Адрес сервиса'][i]}<input value={m[k]||''} onChange={e=>field(k,e.target.value)}/></label>)}<label>Теги через запятую<input value={(m.tags||[]).join(', ')} onChange={e=>field('tags',e.target.value.split(',').map(s=>s.trim()))}/></label><label>Файл оригинала (SRC-ID)<input value={m.fileId||''} onChange={e=>field('fileId',e.target.value)}/></label><label>Вложения через запятую<input value={(m.attachments||[]).join(',')} onChange={e=>field('attachments',e.target.value.split(',').map(s=>s.trim()).filter(Boolean))}/></label></div>
 <h2>Юридическая проверка</h2><div className="form-grid"><label>Статус проверки<select value={m.legalStatus} onChange={e=>field('legalStatus',e.target.value)}><option value="unverified">Не проверено</option><option value="verified">Проверено</option></select></label><label>Дата новой проверки<input type="date" value={m.legalDate||''} onChange={e=>field('legalDate',e.target.value)}/></label><label>Основание проверки<input value={m.legalBasis||''} onChange={e=>field('legalBasis',e.target.value)}/></label><label>Дата в исходнике<input value={m.sourceDate||''} onChange={e=>field('sourceDate',e.target.value)}/></label></div>
 <h2>Шаги инструкции</h2>{m.steps.map((s,i)=><div className="step-editor" key={s.id}><h3>Шаг {i+1}</h3><label>Действие<textarea aria-label="Действие" rows={5} value={s.text} onChange={e=>field('steps',m.steps.map((x,j)=>j===i?{...x,text:e.target.value}:x))}/></label>{['important','reference'].map((k,j)=><label key={k}>{j?'Справочно':'Важно'}<textarea value={s[k]||''} onChange={e=>field('steps',m.steps.map((x,n)=>n===i?{...x,[k]:e.target.value}:x))}/></label>)}<label>Файлы шага через запятую<input value={(s.attachments||[]).join(',')} onChange={e=>field('steps',m.steps.map((x,j)=>j===i?{...x,attachments:e.target.value.split(',').map(s=>s.trim()).filter(Boolean)}:x))}/></label><button disabled={i===0} onClick={()=>{const a=[...m.steps];[a[i],a[i-1]]=[a[i-1],a[i]];field('steps',remapSteps(m.steps,a))}}>Выше</button><button disabled={i===m.steps.length-1} onClick={()=>{const a=[...m.steps];[a[i],a[i+1]]=[a[i+1],a[i]];field('steps',remapSteps(m.steps,a))}}>Ниже</button><button onClick={()=>field('steps',remapSteps(m.steps,m.steps.filter((_,j)=>j!==i)))}>Удалить шаг</button></div>)}<button onClick={()=>field('steps',[...m.steps,{id:crypto.randomUUID(),text:'',attachments:[],branches:[]}])}>Добавить шаг</button><details><summary>Развилки и полный текст (структурные поля)</summary><JsonField label="Шаги и развилки: index – номер шага с нуля" value={m.steps} onChange={x=>field('steps',x)} notify={notify}/><JsonField label="Блоки оригинального фрагмента" value={m.blocks} onChange={x=>field('blocks',x)} notify={notify}/></details></div>
 <section className="panel"><h2>Происхождение</h2><p>{m.sourceId} · {m.sourceName}</p>{m.sourceId&&<><a href={fileUrl(m.sourceId)} target="_blank">Открыть закрытый оригинал</a><button onClick={()=>api('/api/admin/sources/'+m.sourceId).then(setOriginal)}>Показать исходные блоки</button></>}{original&&<Blocks blocks={original.blocks.map(b=>b.data)}/>}</section>
 <section className="panel"><h2>История версий</h2>{versions.map(v=><div className="version-row" key={v.id}><span>v{v.revision} · {v.actor} · {new Date(v.created).toLocaleString('ru')}</span><button onClick={()=>setCompare(v.data)}>Сравнить</button><button onClick={async()=>{try{await api('/api/admin/restore/'+id+'/'+v.revision,{method:'POST',body:{revision:m.revision}});load();notify('Версия восстановлена со статусом проверки')}catch(e){notify(e.message)}}}>Восстановить</button></div>)}{compare&&<div className="overview-grid"><pre>{JSON.stringify(compare,null,2)}</pre><pre>{JSON.stringify(m,null,2)}</pre></div>}</section></>;
}
function JsonField({label,value,onChange,notify}){const [raw,setRaw]=useState(JSON.stringify(value,null,2));return <label>{label}<textarea rows={10} value={raw} onChange={e=>setRaw(e.target.value)}/><button onClick={()=>{try{onChange(JSON.parse(raw));notify('Структура применена. Нажмите «Сохранить».')}catch{notify('Ошибка JSON')}}}>Применить структуру</button></label>}
function Sources({notify,user}){const [sources,setSources]=useState([]),[selected,setSelected]=useState(null),[report,setReport]=useState(null);useEffect(()=>{api('/api/admin/sources').then(setSources)},[]);return <><div className="notice">Все оригиналы доступны только уполномоченным пользователям. Импорт читает локальный комплект, не принимает произвольные архивы из браузера.</div>{user.role==='admin'&&<div className="filters"><button onClick={()=>api('/api/admin/import',{method:'POST',body:{dryRun:true}}).then(setReport).catch(e=>notify(e.message))}>Предварительная проверка импорта</button><button disabled={!report?.dryRun} onClick={()=>api('/api/admin/import',{method:'POST',body:{dryRun:false}}).then(r=>{setReport(r);notify('Импорт сохранён')}).catch(e=>notify(e.message))}>Подтвердить импорт</button></div>}{report&&<pre>{JSON.stringify(report,null,2)}</pre>}<label>Источник<select value={selected?.source?.id||''} onChange={e=>api('/api/admin/sources/'+e.target.value).then(setSelected)}><option value="">Выберите из {sources.length} файлов</option>{sources.map(s=><option key={s.id} value={s.id}>{s.id} · {s.path.split('/').pop()} · {s.kind}</option>)}</select></label>{selected?.source&&<><h2>{selected.source.id}</h2><a href={fileUrl(selected.source.id)} target="_blank">Скачать оригинал</a><p>SHA-256: <code>{selected.source.sha256}</code></p>{selected.blocks.map(b=><details className="panel" key={b.id}><summary>{b.locator} · {b.outcome} · {b.reason||b.entity_id}</summary><Blocks blocks={[b.data]}/></details>)}</>}</>}
function Stats(){const [s,set]=useState(null);useEffect(()=>{api('/api/admin/stats').then(set)},[]);return s?<><div className="metrics"><div className="panel"><strong>{s.sources}</strong> исходников</div><div className="panel"><strong>{s.blocks}</strong> блоков</div><div className="panel"><strong>{s.unresolved.length}</strong> неразрешённых ссылок</div></div><h2>Материалы по статусам</h2>{s.statuses.map(x=><p key={x.status}>{labels[x.status]}: {x.count}</p>)}<h2>Обработка блоков</h2>{s.outcomes.map(x=><p key={x.outcome}>{x.outcome}: {x.count}</p>)}<details><summary>Неразрешённые связи</summary><pre>{JSON.stringify(s.unresolved,null,2)}</pre></details><details><summary>Предложения обновления источников</summary><pre>{JSON.stringify(s.proposals,null,2)}</pre></details><p>Сбор персональных поисковых запросов и просмотров отключён.</p></>:<p>Загрузка…</p>}
function Taxonomy({notify}){const [items,set]=useState([]);const load=()=>api('/api/admin/taxonomy').then(set);useEffect(()=>{load()},[]);return <><form className="panel" onSubmit={async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));await api('/api/admin/taxonomy/'+(d.id||crypto.randomUUID()),{method:'PUT',body:d});load();notify('Сохранено')}}><label>ID для изменения (пусто – создать)<input name="id"/></label><label>Тип<select name="kind">{['Категория','Этап','Тег','Чек-лист'].map(k=><option key={k}>{k}</option>)}</select></label><label>Название<input name="title" required/></label><label>Пункты или описание<textarea name="text"/></label><button className="primary">Сохранить</button></form>{items.map(x=><div className="panel" key={x.id}><h2>{x.title}</h2><p>{x.kind} · {x.id}</p><p className="preserve">{x.text}</p></div>)}</>}
function Professions({catalog,notify}){return catalog.map(p=><form className="panel" key={p.id} onSubmit={async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));await api('/api/admin/professions/'+p.id,{method:'PUT',body:d});notify('Направление сохранено')}}><label>Название<input name="title" defaultValue={p.title}/></label><label>Состояние материалов<textarea name="note" defaultValue={p.note}/></label><button>Сохранить</button></form>)}
function Users({notify}){const [u,set]=useState([]);useEffect(()=>{api('/api/admin/users').then(set)},[]);return u.map(x=><div className="panel" key={x.id}><strong>{x.username}</strong><label>Роль<select value={x.role} onChange={async e=>{try{await api('/api/admin/users/'+x.id,{method:'PUT',body:{role:e.target.value}});api('/api/admin/users').then(set);notify('Роль изменена')}catch(e){notify(e.message)}}}>{['reader','editor','admin'].map(r=><option key={r}>{r}</option>)}</select></label></div>)}
