import React,{useEffect,useState} from 'react';
import {api,mirror} from './api';import {parseSnapshot,selectChanges,routeProfessions,brief} from '../shared/changes';
const date=value=>value?new Date(value).toLocaleDateString('ru-RU'):'нет данных';
const instant=value=>value?new Date(value).toLocaleString('ru-RU'):'нет данных';
export function Changes({route,catalog,user,notify}){
 const [data,setData]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);const params=route.params,id=route.path.startsWith('changes/')?route.path.slice(8):null;
 const load=async()=>{try{const r=await fetch(mirror?import.meta.env.BASE_URL+'changes.json':'/api/changes',{cache:'no-store'});if(!r.ok)throw Error('Не удалось загрузить изменения');setData(parseSnapshot(await r.json()));setError('')}catch(e){setError(e.message)}};
 useEffect(()=>{load();const timer=setInterval(load,60000);return()=>clearInterval(timer)},[]);
 const update=(key,value)=>{const next=new URLSearchParams(params);value?next.set(key,value):next.delete(key);if(key!=='page')next.delete('page');location.hash='/changes?'+next;};
 const list='#/changes'+(params.size?'?'+params:'');const chosen=data?.items.find(i=>i.id===id),items=data?selectChanges(data.items,params):[],pages=Math.max(1,Math.ceil(items.length/15)),page=Math.min(pages,Math.max(1,parseInt(params.get('page'))||1));
 const stale=data?.lastPostAt&&Date.now()-Date.parse(data.lastPostAt)>14*86400000;
 return <div className="changes-page"><header className="section-heading"><div><h1>Правовые изменения</h1><p>Справки и обзоры LegisDigest</p></div><a href="https://t.me/LegisDigest" target="_blank" rel="noreferrer">Открыть источник ↗</a></header>
 {error&&<div role="alert" className="notice warning">{error}. {data?'Показана ранее загруженная лента.':''}<button onClick={load}>Повторить</button></div>}
 {data&&<><div className="changes-status"><span>Последняя публикация: <strong>{date(data.lastPostAt)}</strong></span><span>Получено навигатором: {instant(data.navigatorSync.receivedAt)}</span><span>Источник проверен: {instant(data.lastSuccessAt)}</span></div>{(data.navigatorSync.status!=='ok'||data.syncStatus!=='ok')&&<p className="notice warning">Обновление временно недоступно. Сохранён последний доступный выпуск.</p>}{stale&&<p className="notice">В источнике нет новых публикаций более двух недель. Дата загрузки не означает появления новых изменений.</p>}
 {!mirror&&['editor','admin'].includes(user?.role)&&<button disabled={busy} onClick={async()=>{setBusy(true);try{const r=await api('/api/admin/changes/sync',{method:'POST',body:{}});await load();notify(r.status==='ok'?'Лента обновлена':'Источник недоступен; сохранён прежний выпуск')}catch(e){notify(e.message)}finally{setBusy(false)}}}>{busy?'Проверяем источник…':'Обновить из LegisDigest'}</button>}
 {id?chosen?<ChangeDetail key={id} item={chosen} catalog={catalog} back={list} notify={notify}/>:<section className="empty"><h2>Изменение не найдено</h2><a href={list}>К списку изменений</a></section>:<><div className="segmented" aria-label="Разделы изменений">{[['digest','Справки и обзоры'],['act','Архив актов'],['all','Всё']].map(([key,title])=><button key={key} aria-pressed={(params.get('view')||'digest')===key} className={(params.get('view')||'digest')===key?'selected':''} onClick={()=>update('view',key)}>{title}</button>)}</div>
 <div className="filters changes-filters"><label>Поиск по изменениям<input type="search" value={params.get('q')||''} onChange={e=>update('q',e.target.value)} placeholder="Тема, номер акта или фраза"/></label><label>Подборка по профессии<select aria-label="Подборка по профессии" value={params.get('profession')||''} onChange={e=>update('profession',e.target.value)}><option value="">Для всех профессий</option>{catalog.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select></label></div><details className="changes-extra"><summary>Рубрика, даты и порядок</summary><div className="filters"><label>Рубрика<select aria-label="Рубрика" value={params.get('topic')||''} onChange={e=>update('topic',e.target.value)}><option value="">Все рубрики</option>{[...new Set(data.items.map(i=>i.topic))].sort().map(t=><option key={t}>{t}</option>)}</select></label><label>Опубликовано с<input type="date" value={params.get('from')||''} onChange={e=>update('from',e.target.value)}/></label><label>Опубликовано по<input type="date" value={params.get('to')||''} onChange={e=>update('to',e.target.value)}/></label><label>Порядок<select aria-label="Порядок изменений" value={params.get('sort')||'newest'} onChange={e=>update('sort',e.target.value)}><option value="newest">Сначала новые</option><option value="oldest">Сначала старые</option></select></label></div></details>
 <p className="changes-note">Подборки сформированы по темам текста. Они не определяют круг лиц, на которых юридически распространяется норма. Даты фильтра – даты публикаций.</p><div className="section-heading"><p role="status">Найдено: {items.length}</p><a href="#/changes">Сбросить фильтры</a></div>{params.get('from')&&params.get('to')&&params.get('from')>params.get('to')&&<p role="alert">Конец периода должен быть не раньше начала.</p>}
 <div className="changes-list">{items.slice((page-1)*15,page*15).map(item=><article key={item.id} className="change-row"><div className="meta"><time>{date(item.published)}</time><span>{item.topic}</span></div><h2><a href={'#/changes/'+item.id+(params.size?'?'+params:'')}>{item.title}</a></h2><p>{item.entryType==='digest'?item.summary:'Реквизиты акта и ссылка на официальный текст. Краткая справка пока не подготовлена.'}</p><small>{item.entryType==='digest'?'Автоматический материал источника · проверка человеком не подтверждена':'Архив реквизитов · текущая редакция не проверена'}</small><div className="change-tags">{routeProfessions(item).map(id=><button key={id} onClick={()=>update('profession',id)}>{catalog.find(p=>p.id===id)?.title||id}</button>)}</div></article>)}</div>{!items.length&&<div className="empty">По этим условиям ничего не найдено. <a href="#/changes">Показать все изменения</a></div>}<div className="pagination"><button disabled={page===1} onClick={()=>update('page',String(page-1))}>Назад</button><span>{page} / {pages}</span><button disabled={page===pages} onClick={()=>update('page',String(page+1))}>Далее</button></div></>}
 </>}{!data&&!error&&<p role="status">Загрузка изменений…</p>}</div>;
}
function ChangeDetail({item,catalog,back,notify}){const [expanded,setExpanded]=useState(false),[manual,setManual]=useState(''),short=brief(item),professions=routeProfessions(item);return <article className="change-detail"><a href={back}>← К списку изменений</a><div className="meta">{item.topic} · {date(item.published)}</div><h2>{item.title}</h2><p className="notice">{item.entryType==='digest'?'Автоматический материал LegisDigest. Справка ниже состоит из фрагментов источника; проверка человеком не подтверждена.':'Архив акта. Действующая редакция и дата вступления в силу не подтверждены.'}</p><div className="detail-tools"><a href={item.url} target="_blank" rel="noreferrer">{item.entryType==='digest'?'Пост LegisDigest':'Официальный текст'} ↗</a><button onClick={async()=>{const url=location.href.split('#')[0]+'#/changes/'+item.id;try{await navigator.clipboard.writeText(url);notify('Ссылка скопирована')}catch{setManual(url)}}}>Скопировать ссылку</button></div>{manual&&<label>Постоянная ссылка<input readOnly value={manual} onFocus={e=>e.target.select()}/></label>}
 {professions.length>0&&<section><h3>Подборки по теме</h3><div className="change-tags">{professions.map(id=><a key={id} href={'#/changes?profession='+id}>{catalog.find(p=>p.id===id)?.title||id}</a>)}</div></section>}
 {item.entryType==='digest'?<><h3>Краткая справка по источнику</h3><section className="panel"><h4>О чём материал</h4>{short.what.slice(0,2).map((s,i)=><p className="preserve" key={i}>{s}</p>)}<h4>Даты в сообщении</h4>{short.dates.length?short.dates.map((s,i)=><p className="preserve" key={i}>{s}</p>):<p>Единая дата не установлена. Проверьте сроки для каждого акта в первоисточнике.</p>}<h4>Действия, предложенные источником</h4>{short.actions.length?short.actions.slice(0,2).map((s,i)=><p className="preserve" key={i}>{s}</p>):<p>Отдельный перечень действий в сообщении не выделен.</p>}</section><button aria-expanded={expanded} onClick={()=>setExpanded(!expanded)}>{expanded?'Свернуть полный текст':'Читать полный материал'}</button>{expanded&&<section className="changes-source">{item.blocks.map((block,i)=>{const content=block.segments.map((s,j)=>s.url?<a key={j} href={s.url} target="_blank" rel="noreferrer">{s.text}</a>:<React.Fragment key={j}>{s.text}</React.Fragment>);return block.heading?<h3 key={i}>{content}</h3>:<p key={i}>{content}</p>})}</section>}</>:<section className="panel"><h3>Реквизиты</h3><p>{item.kind} · № {item.number||'не указан'}</p><p>Дата акта: {date(item.date)}. Опубликован: {date(item.published)}.</p><p>Краткая справка к этому архивному акту пока не подготовлена.</p></section>}
 <section><h3>Инструкции навигатора по теме</h3><div className="change-tags">{professions.map(id=><a key={id} href={"#/home?profession="+id}>{catalog.find(p=>p.id===id)?.title||id}</a>)}{!professions.length&&<a href="#/home">Все инструкции</a>}</div></section><p className="changes-note">Сообщение может объединять принятые нормы, законопроекты и новости. Перед применением сверьте стадию, редакцию и сроки по официальному документу.</p></article>}
