import React,{useEffect,useState} from 'react';
import {api,labels,fileUrl} from './api';
import {Blocks} from './reader';
import {remapSteps} from '../shared/steps';
const panes=[['main','Карточка'],['steps','Шаги инструкции'],['files','Документы и ссылки'],['legal','Правовая проверка'],['history','История и источник']];
const fields={situation:'Ситуация',audience:'Адресат',side:'Сторона',scope:'Границы применения',urgency:'Срочность',deadlines:'Сроки',legal:'Юридически точно',simple:'Простыми словами',documents:'Что подготовить',errors:'Чего не делать',norms:'Правовое основание',editorNote:'Заметка редактору',category:'Категория',stage:'Этап',url:'Адрес сервиса'};
export function Editor({id,notify,catalog,initialPane='main'}){
 const [m,set]=useState(null),[baseline,setBaseline]=useState(''),[pane,setPane]=useState(initialPane),[active,setActive]=useState(0),[versions,setVersions]=useState([]),[forms,setForms]=useState([]),[original,setOriginal]=useState(null),[compare,setCompare]=useState(null),[preview,setPreview]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const dirty=!!m&&JSON.stringify(m)!==baseline;
 const accept=x=>{set(x);setBaseline(JSON.stringify(x));};
 const history=()=>api('/api/admin/versions/'+id).then(setVersions).catch(e=>setError(e.message));
 useEffect(()=>{let alive=true;api('/api/materials/'+id).then(x=>{if(alive)accept(x)}).catch(e=>setError(e.message));history();api('/api/materials?kind=form&admin=1&limit=1000').then(x=>setForms(x.items)).catch(e=>setError(e.message));return()=>{alive=false}},[id]);
 useEffect(()=>{if(!dirty)return;const unload=e=>{e.preventDefault();e.returnValue=''};const link=e=>{const a=e.target.closest('a');if(a?.getAttribute('href')?.startsWith('#')&&!confirm('Есть несохранённые изменения. Уйти без сохранения?')){e.preventDefault();e.stopPropagation()}};addEventListener('beforeunload',unload);document.addEventListener('click',link,true);return()=>{removeEventListener('beforeunload',unload);document.removeEventListener('click',link,true)}},[dirty]);
 const save=async status=>{setBusy(true);setError('');try{const saved=await api('/api/admin/materials/'+id,{method:'PUT',body:{...m,...(status?{status}:{})}});accept(saved);history();notify('Версия '+saved.revision+' сохранена');return saved}catch(e){setError(e.message);notify(e.message)}finally{setBusy(false)}};
 if(!m)return <p role="status">{error||'Загрузка…'}</p>;
 const field=(k,v)=>set(prev=>({...prev,[k]:v}));
 const text=(k,rows=3)=><label key={k}>{fields[k]||k}<textarea aria-label={fields[k]||k} rows={rows} value={m[k]||''} onChange={e=>field(k,e.target.value)}/></label>;
 const step=m.steps[active],updateStep=(k,v)=>field('steps',m.steps.map((s,i)=>i===active?{...s,[k]:v}:s));
 const move=delta=>{const next=[...m.steps],target=active+delta;[next[active],next[target]]=[next[target],next[active]];field('steps',remapSteps(m.steps,next));setActive(target)};
 const duplicate=async()=>{setBusy(true);try{const x=await api('/api/admin/materials',{method:'POST',body:{...m,title:m.title+' (копия)',code:'',status:'draft'}});accept(m);location.hash='/admin/edit/'+x.id}catch(e){setError(e.message)}finally{setBusy(false)}};
 return <div className="material-editor"><div className="editor-actions"><button className="primary" disabled={busy} onClick={()=>save()}>Сохранить</button><button disabled={busy} onClick={()=>setPreview(!preview)}>{preview?'Вернуться к редактированию':'Предпросмотр'}</button><button disabled={busy} onClick={duplicate}>Копировать</button><span className="editor-save-state">{dirty?'Есть несохранённые изменения':'Изменения сохранены'} · v{m.revision}</span></div>
 {error&&<div className="notice warning" role="alert">{error}</div>}
 <div className="editor-heading"><div><small>{m.code||'Без кода'} · {labels[m.kind]}</small><h2>{m.title}</h2></div><span className="pill">{labels[m.status]}</span></div>
 {preview?<EditorPreview m={m} forms={forms}/>:<><nav className="editor-tabs" aria-label="Разделы редактора">{panes.map(([key,title])=><button key={key} aria-pressed={pane===key} className={pane===key?'selected':''} onClick={()=>setPane(key)}>{title}{key==='steps'?' · '+m.steps.length:''}</button>)}</nav>
 <section className="panel editor-form">
 {pane==='main'&&<><h2>Содержание карточки</h2><label>Название<input value={m.title} onChange={e=>field('title',e.target.value)}/></label><div className="form-grid"><label>Тип<select aria-label="Тип" value={m.kind} onChange={e=>field('kind',e.target.value)}>{['card','question','guide','form','service','norm','task','example'].map(k=><option key={k} value={k}>{labels[k]}</option>)}</select></label><label>Профессия<select aria-label="Профессия" value={m.profession} onChange={e=>field('profession',e.target.value)}><option value="">Общие материалы</option>{catalog.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select></label><label>Исходный код<input value={m.code||''} onChange={e=>field('code',e.target.value)}/></label><label>Доступ<select aria-label="Доступ" value={m.accessLevel||'public'} onChange={e=>field('accessLevel',e.target.value)}><option value="public">Открытый</option><option value="subscriber">По подписке</option></select></label>{['category','stage'].map(k=><label key={k}>{fields[k]}<input value={m[k]||''} onChange={e=>field(k,e.target.value)}/></label>)}</div><label>Теги через запятую<input value={(m.tags||[]).join(', ')} onChange={e=>field('tags',e.target.value.split(',').map(s=>s.trim()))}/></label>
 {['situation','audience','side','scope','urgency','deadlines','legal','simple','documents','errors'].map(k=>text(k,k==='legal'||k==='simple'?6:2))}{m.kind==='service'&&<label>Адрес сервиса<input type="url" value={m.url||''} onChange={e=>field('url',e.target.value)}/></label>}{text('editorNote')}
 <h2>Публикация</h2><label>Статус<select aria-label="Статус" value={m.status} onChange={e=>field('status',e.target.value)}>{['draft','review','ready','published','archived'].map(k=><option key={k} value={k}>{labels[k]}</option>)}</select></label><div className="row-actions"><button disabled={busy} onClick={()=>save('review')}>Отправить на проверку</button><button disabled={busy} onClick={()=>save('published')}>Опубликовать</button><button disabled={busy} onClick={()=>save('archived')}>В архив</button></div><small>Кнопки сохраняют текущие правки. Публикация появляется в серверном приложении; публичное зеркало обновляется отдельной сборкой.</small></>}
 {pane==='steps'&&<><div className="section-heading"><h2>Шаги инструкции</h2><button onClick={()=>{field('steps',[...m.steps,{id:crypto.randomUUID(),text:'',attachments:[],branches:[]}]);setActive(m.steps.length)}}>Добавить шаг</button></div><div className="editor-step-layout"><nav className="editor-step-list" aria-label="Выбор шага">{m.steps.map((s,i)=><button key={s.id} aria-current={i===active?'step':undefined} className={i===active?'selected':''} onClick={()=>setActive(i)}><b>{i+1}</b><span>{s.text.trim().split('\n')[0]||'Новое действие'}</span></button>)}</nav>{step?<div className="step-editor" key={step.id}><h3>Шаг {active+1}</h3><label>Действие<textarea aria-label="Действие" rows={8} value={step.text} onChange={e=>updateStep('text',e.target.value)}/></label>{['important','reference'].map((k,i)=><label key={k}>{i?'Справочно':'Важно'}<textarea aria-label={i?'Справочно':'Важно'} value={step[k]||''} onChange={e=>updateStep(k,e.target.value)}/></label>)}<DocumentPicker title="Документы шага" value={step.attachments||[]} forms={forms} onChange={v=>updateStep('attachments',v)}/><h3>Переходы по условию</h3>{(step.branches||[]).map((branch,i)=><div className="branch-editor" key={i}><label>Условие перехода<input value={branch.label||''} onChange={e=>updateStep('branches',step.branches.map((b,j)=>i===j?{...b,label:e.target.value}:b))}/></label><label>Перейти к шагу<select aria-label="Перейти к шагу" value={branch.index} onChange={e=>updateStep('branches',step.branches.map((b,j)=>i===j?{...b,index:Number(e.target.value)}:b))}>{m.steps.map((s,n)=><option key={s.id} value={n}>{n+1}. {s.text.slice(0,60)||'Новое действие'}</option>)}</select></label><button aria-label={'Удалить переход '+(i+1)} onClick={()=>updateStep('branches',step.branches.filter((_,j)=>i!==j))}>Удалить</button></div>)}<button onClick={()=>updateStep('branches',[...(step.branches||[]),{label:'',index:Math.min(active+1,m.steps.length-1)}])}>Добавить переход</button><div className="step-order"><button disabled={!active} onClick={()=>move(-1)}>Выше</button><button disabled={active===m.steps.length-1} onClick={()=>move(1)}>Ниже</button><button onClick={()=>{if(!confirm('Удалить этот шаг и переходы к нему?'))return;field('steps',remapSteps(m.steps,m.steps.filter((_,i)=>i!==active)));setActive(Math.max(0,active-1))}}>Удалить шаг</button></div></div>:<p className="empty">Добавьте первый шаг инструкции.</p>}</div></>}
 {pane==='files'&&<><h2>Документы и ссылки</h2><DocumentPicker title="Документы карточки" value={m.attachments||[]} forms={forms} onChange={v=>field('attachments',v)}/>{m.fileId&&<p>Основной файл: {forms.find(f=>f.fileId===m.fileId)?.title||m.fileId} · <a href={fileUrl(m.fileId)} target="_blank" rel="noreferrer">Открыть оригинал</a></p>}{m.formReview&&<div className="notice">Рабочая версия: <a href={'/current/'+encodeURIComponent(m.formReview.currentFile)} target="_blank" rel="noreferrer">{m.formReview.currentFile}</a><p>{m.formReview.note}</p></div>}{m.supportingTemplates?.map(f=><p key={f.currentFile}><a href={'/current/'+encodeURIComponent(f.currentFile)} target="_blank" rel="noreferrer">{f.title}</a></p>)}<h3>Источники и правовые основания</h3>{(m.externalLinks||[]).map((link,i)=><div className="branch-editor" key={i}><label>Название ссылки<input value={link.label||''} onChange={e=>field('externalLinks',m.externalLinks.map((l,j)=>i===j?{...l,label:e.target.value}:l))}/></label><label>Адрес ссылки<input type="url" value={link.url||''} onChange={e=>field('externalLinks',m.externalLinks.map((l,j)=>i===j?{...l,url:e.target.value}:l))}/></label><button aria-label={'Удалить ссылку '+(i+1)} onClick={()=>field('externalLinks',m.externalLinks.filter((_,j)=>j!==i))}>Удалить</button></div>)}<button onClick={()=>field('externalLinks',[...(m.externalLinks||[]),{label:'',url:''}])}>Добавить ссылку</button><details><summary>Идентификатор основного файла</summary><label>Файл оригинала (SRC-ID)<input value={m.fileId||''} onChange={e=>field('fileId',e.target.value)}/></label><small>Указывайте существующий источник из раздела импорта.</small></details></>}
 {pane==='legal'&&<><h2>Правовая проверка</h2>{text('norms',8)}<div className="form-grid"><label>Статус проверки<select aria-label="Статус проверки" value={m.legalStatus||'unverified'} onChange={e=>field('legalStatus',e.target.value)}><option value="unverified">Не проверено</option><option value="verified">Проверено</option></select></label><label>Дата новой проверки<input type="date" value={m.legalDate||''} onChange={e=>field('legalDate',e.target.value)}/></label><label>Основание проверки<input value={m.legalBasis||''} onChange={e=>field('legalBasis',e.target.value)}/></label><label>Дата в исходнике<input value={m.sourceDate||''} onChange={e=>field('sourceDate',e.target.value)}/></label></div><label>Оговорка об актуальности<textarea aria-label="Оговорка об актуальности" value={m.legalNotice||''} onChange={e=>field('legalNotice',e.target.value)}/></label></>}
 {pane==='history'&&<><h2>История версий</h2>{versions.map(v=><div className="version-row" key={v.id}><span>v{v.revision} · {v.actor} · {new Date(v.created).toLocaleString('ru')}</span><button onClick={()=>setCompare(v.data)}>Сравнить</button><button disabled={busy} onClick={async()=>{if(dirty&&!confirm('Восстановление заменит несохранённые правки. Продолжить?'))return;setBusy(true);try{const x=await api('/api/admin/restore/'+id+'/'+v.revision,{method:'POST',body:{revision:m.revision}});accept(x);history();notify('Версия восстановлена со статусом проверки')}catch(e){setError(e.message)}finally{setBusy(false)}}}>Восстановить</button></div>)}{compare&&<div className="version-comparison"><h3>Отличия выбранной версии</h3>{Object.keys({...compare,...m}).filter(k=>!['revision'].includes(k)&&JSON.stringify(compare[k])!==JSON.stringify(m[k])).map(k=><section key={k}><h4>{fields[k]||({title:'Название',steps:'Шаги',status:'Статус',externalLinks:'Ссылки',attachments:'Документы'}[k])||k}</h4><div className="overview-grid"><div><small>Выбранная версия</small><pre>{typeof compare[k]==='string'?compare[k]:JSON.stringify(compare[k],null,2)}</pre></div><div><small>Текущая редакция</small><pre>{typeof m[k]==='string'?m[k]:JSON.stringify(m[k],null,2)}</pre></div></div></section>)}</div>}<h2>Исходный материал</h2><p>{m.sourceId||'Редакционный материал'} · {m.sourceName||'Создан в навигаторе'}</p>{m.sourceId&&<><a href={fileUrl(m.sourceId)} target="_blank" rel="noreferrer">Открыть закрытый оригинал</a><button onClick={()=>api('/api/admin/sources/'+m.sourceId).then(setOriginal).catch(e=>setError(e.message))}>Показать исходные блоки</button></>}{original&&<Blocks blocks={original.blocks.map(b=>b.data)}/>}<h3>Текст материала</h3>{(m.blocks||[]).map((b,i)=>b.rows?<Blocks key={i} blocks={[b]}/>:<label key={i}>Абзац {i+1}<textarea value={b.text||''} onChange={e=>field('blocks',m.blocks.map((x,j)=>i===j?{...x,text:e.target.value}:x))}/></label>)}<button onClick={()=>field('blocks',[...m.blocks,{text:''}])}>Добавить абзац</button></>}
 </section></>}
 </div>;
}
function DocumentPicker({title,value,forms,onChange}){const [query,setQuery]=useState('');return <fieldset className="document-picker"><legend>{title}</legend><label>Найти документ<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Название или код"/></label><div className="document-options">{forms.filter(f=>(f.title+' '+f.fileId).toLowerCase().includes(query.toLowerCase())).map(f=><label key={f.id}><input type="checkbox" checked={value.includes(f.fileId)} onChange={e=>onChange(e.target.checked?[...new Set([...value,f.fileId])]:value.filter(id=>id!==f.fileId))}/><span>{f.title}<small>{f.fileId} · {labels[f.status]}</small></span></label>)}</div>{value.filter(id=>!forms.some(f=>f.fileId===id)).map(id=><p key={id}>{id} · форма недоступна <button onClick={()=>onChange(value.filter(x=>x!==id))}>Убрать</button></p>)}<small>Выбрано: {value.length}</small></fieldset>}
function EditorPreview({m,forms}){const [step,setStep]=useState(0);const s=m.steps[step];return <section className="editor-preview"><p className="notice">Предпросмотр текущих правок. Материал ещё не сохранён этой кнопкой.</p><div className="step-rail">{m.steps.map((s,i)=><button key={s.id} className={i===step?'selected':''} onClick={()=>setStep(i)}>{i+1}. {s.text.slice(0,90)||'Новое действие'}</button>)}</div><article className="instruction-sheet"><small>{m.code}</small><h1>{m.title}</h1>{m.situation&&<p className="preserve">{m.situation}</p>}{s&&<><h2>Шаг {step+1}</h2>{s.attachments?.map(id=><p key={id}>Документ: {forms.find(f=>f.fileId===id)?.title||id}</p>)}<p className="preserve">{s.text}</p>{s.important&&<div className="notice"><strong>Важно</strong><p className="preserve">{s.important}</p></div>}{s.reference&&<p className="preserve">Справочно: {s.reference}</p>}{s.branches?.map((b,i)=><button key={i} onClick={()=>setStep(b.index)}>{b.label||'Переход'} → {b.index+1}</button>)}</>}{['legal','simple','documents','errors','norms'].map(k=>m[k]&&<section key={k}><h2>{fields[k]}</h2><p className="preserve">{m[k]}</p></section>)}{!m.steps.length&&<Blocks blocks={m.blocks}/>}</article></section>}
