import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Compass,Search,BookOpen,ListChecks,Files,Bookmark,CalendarDays,Bell,Settings,ArrowUpRight,Menu,LogIn,Wrench,ArrowRight,LogOut,UserRound,SlidersHorizontal} from 'lucide-react';
import {api,mirror,labels} from './api';
import {situationSearch,examples} from '../shared/situation-search';
import {ProfessionHome} from './profession-home';
import {Detail} from './reader';
import {Admin} from './admin';
import {LegalQuestions} from './legal-questions';
import {SiteHelp} from './site-help';
import {Changes} from './changes';
import {Account,Privacy} from './account';
import {MobileInstall} from './mobile';
import './style.css';
import './layout.generated.css';
const navigation=[['plan','План на сегодня',CalendarDays],['home','Инструкции',ListChecks],['form','Документы',Files],['situations','Карточки',BookOpen],['question','Вопросы гида',BookOpen],['service','Сервисы',Wrench],['changes','Правовые изменения',BookOpen],['legal-question','Задать правовой вопрос',BookOpen],['favorites','Избранное',Bookmark],['notifications','Уведомления',Bell],['account','Личный кабинет',UserRound]];
export function useRoute(){const [hash,set]=useState(location.hash);useEffect(()=>{const fn=()=>set(location.hash);addEventListener('hashchange',fn);return()=>removeEventListener('hashchange',fn)},[]);const [path,query='']=hash.replace(/^#\/?/,'').split('?');return {path:path||'home',params:new URLSearchParams(query)};}
export const go=(path,params={})=>{const q=new URLSearchParams(Object.entries(params).filter(([,v])=>v!==''&&v!=null));location.hash='/'+path+(q.size?'?'+q:'');};
export function App(){
 const route=useRoute(),[user,setUser]=useState(null),[catalog,setCatalog]=useState([]),[menu,setMenu]=useState(false),[layout,setLayout]=useState(localStorage.getItem('navigator-layout')||'auto'),[selectedProfession,setSelectedProfession]=useState(localStorage.getItem('navigator-profession')||''),[message,setMessage]=useState(''),[personal,setPersonal]=useState({items:[],notifications:[]});
 useEffect(()=>{const valid=['auto','mobile','desktop'].includes(layout)?layout:'auto';document.documentElement.dataset.layout=valid;localStorage.setItem('navigator-layout',valid);document.querySelector('meta[name=viewport]').content=valid==='desktop'?'width=1200':'width=device-width, initial-scale=1.0, viewport-fit=cover';setMenu(false)},[layout]);
 const notify=s=>{setMessage(s);setTimeout(()=>setMessage(''),6500)};
 useEffect(()=>{const expired=()=>{setUser(null);notify('Сеанс завершён. Войдите снова.')};addEventListener('navigator-session-expired',expired);return()=>removeEventListener('navigator-session-expired',expired)},[]);
 const refresh=()=>api('/api/personal').then(setPersonal).catch(e=>notify(e.message));
 useEffect(()=>{api('/api/me').then(x=>setUser(x.user)).catch(()=>setUser(null));api('/api/catalog').then(setCatalog).catch(e=>notify(e.message));},[]);
 useEffect(()=>{if(user)refresh();else setPersonal({items:[],notifications:[]});},[user]);
 useEffect(()=>{if(user&&route.path==='notifications')refresh()},[route.path,user?.id]);
 useEffect(()=>{setMenu(false);if(route.path.startsWith('item/'))window.scrollTo(0,0)},[route.path]);
 useEffect(()=>{if(!menu)return;const previous=document.activeElement;document.querySelector('.sidebar-close')?.focus();const key=e=>{if(e.key==='Escape')setMenu(false);if(e.key==='Tab'){const items=[...document.querySelectorAll('.sidebar button,.sidebar a,.sidebar select')].filter(x=>x.offsetParent!==null&&!x.disabled);const first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}};const resize=()=>{if(innerWidth>760&&layout!=='mobile')setMenu(false)};addEventListener('keydown',key);addEventListener('resize',resize);return()=>{removeEventListener('keydown',key);removeEventListener('resize',resize);if(previous?.isConnected)previous.focus()}},[menu,layout]);
 useEffect(()=>{if(route.params.has('profession')){setSelectedProfession(route.params.get('profession'));localStorage.setItem('navigator-profession',route.params.get('profession'));}},[route.params.toString()]);
 const profession=route.path.startsWith('changes')?(route.params.get('profession')||''):(route.params.get('profession')??selectedProfession);
 const chooseProfession=value=>{setSelectedProfession(value);localStorage.setItem('navigator-profession',value);if(route.path.startsWith('admin')){go('admin',{tab:route.params.get('tab')||'materials',profession:value});return}go(route.path==='legal-question'?'legal-question':route.path.startsWith('changes')?'changes':['home','card','situations','form','question','service'].includes(route.path)?route.path:'home',{profession:value});};
 const navHref=id=>'#/'+id+(profession?'?profession='+encodeURIComponent(profession):'');
 const logout=async()=>{await api('/api/logout',{method:'POST'});setUser(null);go('home',{profession});};
 const authProps={user,personal,refresh,notify,catalog,profession};
 return <><a href="#main" className="skip" onClick={e=>{e.preventDefault();document.getElementById('main')?.focus()}}>К содержанию</a>{menu&&<button className="menu-overlay" aria-label="Закрыть меню по фону" onClick={()=>setMenu(false)}/>}<aside className={menu?'sidebar open':'sidebar'}><button className="sidebar-close" aria-label="Закрыть меню" onClick={()=>setMenu(false)}>×</button><a className="brand" href={navHref('home')}><span className="brand-mark">НП</span><span>НАВИГАТОР<small>ПРОФЕССИЙ</small></span></a><label className="profession-select"><span>Профессия</span><select aria-label="Выбрать профессию" disabled={route.path.startsWith("admin/edit/")} value={profession} onChange={e=>chooseProfession(e.target.value)}><option value="">Все профессии</option>{catalog.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select></label><nav aria-label="Основное меню">{navigation.filter(([id])=>!mirror||!['plan','favorites','notifications','account'].includes(id)).map(([id,label,Icon])=><a key={id} className={route.path===id||(id==='changes'&&route.path.startsWith('changes/'))||(id==='home'&&route.path==='card')?'active':''} href={navHref(id)}><Icon size={24}/>{label}</a>)}{!mirror&&['editor','admin'].includes(user?.role)&&<a className={route.path.startsWith('admin')?'active':''} href="#/admin"><Settings size={24}/>Администрирование</a>}</nav><div className="side-bottom"><label className="layout-select">Версия интерфейса<select aria-label="Версия интерфейса" value={layout} onChange={e=>setLayout(e.target.value)}><option value="auto">Автоматически</option><option value="mobile">Мобильная версия</option><option value="desktop">Полная версия</option></select></label><MobileInstall/><a className="privacy-link" href="#/privacy">Персональные данные</a>{!mirror&&user&&<a href={navHref('plan')} className="today-summary">План на сегодня<span>{personal.items.filter(x=>x.kind==='task'&&!x.data.done).length?`Задач: ${personal.items.filter(x=>x.kind==='task'&&!x.data.done).length}`:'Нет незавершённых задач'}</span></a>}{mirror?<p>Публичная версия<br/>Только просмотр</p>:<div className="profile-row"><span className="avatar"><UserRound size={22}/></span>{user?<><span>{user.username}<small>{({reader:'Читатель',editor:'Редактор',admin:'Администратор'})[user.role]}</small></span><button aria-label="Выйти" onClick={logout}><LogOut size={22}/></button></>:<button onClick={()=>go('login')}>Войти</button>}</div>}</div></aside>
 <div inert={menu?true:undefined} className={'workspace'+(route.path.startsWith('item/')?' reading':'')}><header className="topbar"><button className="mobile-toggle" aria-label="Открыть меню" onClick={()=>setMenu(!menu)}><Menu/></button><span>Навигатор профессий</span>{mirror?<span>Только просмотр</span>:!user?<button onClick={()=>go('login')}>Войти</button>:<button onClick={logout}>{user.username} · Выйти</button>}</header>
 <main id="main" tabIndex={-1}>{(route.path==='changes'||route.path.startsWith('changes/'))?<Changes route={route} {...authProps}/>:route.path==='legal-question'?<LegalQuestions route={route} {...authProps}/>:route.path==='account'?<Account {...authProps}/>:route.path==='privacy'?<Privacy/>:route.path==='login'?<Login onLogin={u=>{setUser(u);go(route.params.get('next')==='legal-question'?'legal-question':'home',{profession,...(route.params.get('next')==='legal-question'?Object.fromEntries([...route.params].filter(([k])=>k!=='next')):{})})}} notify={notify}/>:route.path.startsWith('item/')?<Detail id={route.path.slice(5)} route={route} {...authProps}/>:route.path.startsWith('admin')?<Admin route={route} {...authProps}/>:['plan','favorites','notifications'].includes(route.path)?<Personal section={route.path} {...authProps}/>:<Catalog personal={personal} user={user} route={route} catalog={catalog} profession={profession} notify={notify}/>}</main><nav className="mobile-nav" aria-label="Быстрый доступ"><a className={route.path==='home'?'active':''} href={navHref('home')}><ListChecks size={21}/>Инструкции</a><a className={route.path==='form'?'active':''} href={navHref('form')}><Files size={21}/>Документы</a>{!mirror&&<a className={route.path==='account'?'active':''} href="#/account"><UserRound size={21}/>Кабинет</a>}<button onClick={()=>setMenu(true)}><Menu size={21}/>Меню</button></nav></div><SiteHelp route={route} user={user}/>{message&&<div className="toast" role="status">{message}</div>}</>;

}
function Login({onLogin,notify}){return <section className="login panel"><h1>Вход в навигатор</h1><form onSubmit={async e=>{e.preventDefault();const d=new FormData(e.currentTarget);try{const r=await api('/api/login',{method:'POST',body:Object.fromEntries(d)});onLogin(r.user)}catch(e){notify(e.message)}}}><label>Логин<input name="username" autoComplete="username" required/></label><label>Пароль<input name="password" type="password" autoComplete="current-password" required/></label><button className="primary">Войти</button></form></section>}
function Catalog({route,catalog,profession,notify,personal,user}){
 const [result,setResult]=useState({items:[],total:0}),[busy,setBusy]=useState(true),[facets,setFacets]=useState([]);const q=route.params.get('q')||'',kind=['home','situations'].includes(route.path)?'card':route.path,page=Number(route.params.get('page'))||1;const prof=catalog.find(p=>p.id===profession);
 useEffect(()=>{let active=true;setBusy(true);api('/api/materials?'+new URLSearchParams({...Object.fromEntries(route.params),q:'',page:1,profession,kind:q?'':kind,limit:1000})).then(r=>{if(active){let rows=q?situationSearch(r.items,q):r.items;if(q){const files=new Set(rows.filter(m=>m.kind==='card').flatMap(m=>[...(m.attachments||[]),...(m.steps||[]).flatMap(s=>s.attachments||[])]));const related=r.items.filter(m=>m.kind==='form'&&files.has(m.fileId)&&!rows.some(x=>x.id===m.id));rows=[...rows.filter(m=>m.kind==='card'),...rows.filter(m=>m.kind==='form'),...related,...rows.filter(m=>!['card','form'].includes(m.kind))];}setResult({items:rows.slice((page-1)*18,page*18),total:rows.length})}}).catch(e=>notify(e.message)).finally(()=>active&&setBusy(false));return()=>{active=false}},[route.path,route.params.toString(),profession]);
 useEffect(()=>{if(kind==='card')api('/api/materials?'+new URLSearchParams({kind,profession,limit:1000})).then(r=>setFacets(r.items)).catch(()=>{})},[kind,profession]);
 useEffect(()=>{if(busy)return;const key='navigator-scroll:'+location.hash;requestAnimationFrame(()=>window.scrollTo(0,Number(sessionStorage.getItem(key)||0)));const save=()=>sessionStorage.setItem(key,String(window.scrollY));addEventListener('scroll',save);return()=>removeEventListener('scroll',save)},[busy,route.params.toString()]);
 const filter=(key,value)=>go(route.path,{...Object.fromEntries(route.params),page:1,profession,[key]:value});
 return <><div className="page-intro"><h1>{route.path==='card'?'Инструкции':navigation.find(x=>x[0]===route.path)?.[1]}</h1></div>
 <form className="searchbox" onSubmit={e=>{e.preventDefault();filter('q',new FormData(e.currentTarget).get('q'))}}><Search size={24}/><input key={q} name="q" aria-label="Поиск по ситуации" defaultValue={q} placeholder="Что произошло или что нужно сделать?"/><button className="primary">Найти</button>{q&&<button type="button" onClick={()=>filter('q','')} aria-label="Очистить поиск">×</button>}</form>
 {route.path==='home'&&<div className="search-examples">{(examples[profession]||facets.slice(0,2).map(m=>m.title)).map(text=><button key={text} onClick={()=>filter('q',text)}>{text}</button>)}</div>}
 <details className="catalog-filters"><summary>Дополнительные фильтры</summary><div className="filters"><label>Сортировка<select value={route.params.get('sort')||'asc'} onChange={e=>filter('sort',e.target.value)}><option value="asc">По названию: А–Я</option><option value="desc">По названию: Я–А</option></select></label>{kind==='card'&&['side','urgency'].map((k,i)=><label key={k}>{i?'Срочность':'Сторона'}<select value={route.params.get(k)||''} onChange={e=>filter(k,e.target.value)}><option value="">Все</option>{[...new Set(facets.map(m=>m[k]).filter(Boolean))].map(v=><option key={v} value={v}>{v}</option>)}</select></label>)}</div></details>
 {prof&&<div className="notice"><strong>{prof.title}</strong><p>{prof.note}</p>{prof.coverageNote&&<p>{prof.coverageNote}</p>}{prof.subprofessions&&<p>{prof.subprofessions.join(' · ')}</p>}</div>}
 {route.path==='home'&&!q&&profession&&<ProfessionHome profession={profession} items={facets} personal={personal} user={user}/>}
 <div className="section-heading"><h2>{q?'Результаты поиска':prof?.title||'Все профессии'}</h2><span>{busy?'Загрузка…':`${result.total} записей`}</span></div>
 {busy?<div className="loading" role="status">Загружаем материалы…</div>:result.items.length?<div className="material-list">{result.items.map(m=><MaterialRow key={m.id} m={m} back={location.hash} view={route.path==='situations'?'card':undefined}/>)}</div>:<div className="empty"><BookOpen size={34}/><h2>{q?'Ничего не найдено':'Материалы готовятся'}</h2><p>{q?'Попробуйте другую формулировку или сбросьте фильтры.':'Для этого раздела пока нет опубликованных материалов. Исходники и задачи доступны редактору.'}</p><button onClick={()=>{localStorage.removeItem('navigator-profession');location.hash='/home?profession='}}>Все профессии</button></div>}
 {result.total>18&&<div className="pagination"><button disabled={page===1} onClick={()=>filter('page',page-1)}>Назад</button><span>{page} / {Math.ceil(result.total/18)}</span><button disabled={page*18>=result.total} onClick={()=>filter('page',page+1)}>Далее</button></div>}</>;
}
export function MaterialRow({m,back,view}){return <a className="material-row" href={'#/item/'+m.id+'?'+new URLSearchParams({...(back?{back}:{}),...(view?{view}:{})})}><span className="material-icon">{m.kind==='form'?<Files/>:m.kind==='card'?<ListChecks/>:<BookOpen/>}</span><div><div className="meta"><span>{labels[m.kind]}</span>{m.contentOrigin==='uploaded'&&<span>Загружен редактором</span>}{m.contentOrigin==='editorial'&&<span>Редакционная памятка</span>}{m.locked&&<span className="access-badge">По подписке</span>}{m.code&&<code>{m.code}</code>}</div><h3>{m.title}</h3>{m.situation!==m.title&&<p>{(m.situation||m.simple||m.legal||m.blocks?.find(b=>b.text)?.text||'').slice(0,170)}</p>}</div><ArrowUpRight size={19}/></a>}
function Personal({section,user,personal,refresh,notify}){
 const [saved,setSaved]=useState([]);useEffect(()=>{Promise.all(personal.items.filter(x=>section==='favorites'?x.kind==='favorite':x.kind==='progress').map(x=>api('/api/materials/'+x.item).then(m=>({...m,progress:x.data})).catch(()=>null))).then(x=>setSaved(x.filter(Boolean)))},[section,personal]);
 if(mirror||!user)return <div className="empty"><h1>{navigation.find(x=>x[0]===section)?.[1]}</h1><p>{mirror?'Откройте серверное приложение для сохранения плана.':'Войдите, чтобы сохранять прогресс и задачи.'}</p>{!mirror&&<button onClick={()=>go('login')}>Войти</button>}</div>;
 const update=async(path,body,method='PUT')=>{try{await api(path,{method,body});refresh()}catch(e){notify(e.message)}};
 return <><h1>{navigation.find(x=>x[0]===section)?.[1]}</h1>{section==='notifications'?<>{personal.notifications.length?personal.notifications.map(n=><div className="panel" key={n.id}><h2>{n.title}</h2><p>{n.read?'Прочитано':'Новое уведомление'}</p>{n.questionId&&<a href={'#/legal-question?id='+n.questionId}>Открыть ответ</a>}{n.materialId&&<a href={'#/item/'+n.materialId}>Открыть материал</a>}<button disabled={!!n.read} onClick={()=>update('/api/notifications/'+n.id,{})}>Отметить прочитанным</button></div>):<p className="empty">Уведомлений нет.</p>}</>:<>{saved.map(m=><div key={m.id}><MaterialRow m={m}/>{section==='plan'&&<p className="progress-caption">Выполнено {m.progress.done?.length||0} из {m.steps.length} · <a href={'#/item/'+m.id+'?step='+(m.progress.current||0)}>Продолжить с последнего шага</a></p>}</div>)}{!saved.length&&<p className="notice">{section==='plan'?'Начните инструкцию и отметьте первый шаг.':'Добавляйте материалы в избранное на странице вопроса или инструкции.'}</p>}{section==='plan'&&<><h2>Мои задачи</h2><form className="panel task-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);update('/api/personal/task/'+crypto.randomUUID(),{title:f.get('title'),due:f.get('due'),done:false});e.currentTarget.reset()}}><label>Задача<input name="title" required/></label><label>Мой срок<input name="due" type="date"/></label><button className="primary">Добавить</button><small>Срок задачи задаётся вручную.</small></form>{personal.items.filter(x=>x.kind==='task').map(t=><div className="task panel" key={t.item}><label><input type="checkbox" checked={!!t.data.done} onChange={e=>update('/api/personal/task/'+t.item,{...t.data,done:e.target.checked})}/>{t.data.title}</label><span>{t.data.due||'Без срока'}{!t.data.done&&t.data.due&&t.data.due<new Date().toISOString().slice(0,10)?' · Просрочена':''}</span><button onClick={()=>update('/api/personal/task/'+t.item,null,'DELETE')}>Удалить</button></div>)}</>}</>}</>;
}
createRoot(document.getElementById('root')).render(<App/>);
