import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Compass,Search,BookOpen,ListChecks,Files,Bookmark,CalendarDays,Bell,Settings,ArrowUpRight,Menu,LogIn,Wrench,ArrowRight} from 'lucide-react';
import {api,mirror,labels} from './api';
import {Detail} from './reader';
import {Admin} from './admin';
import './style.css';
const navigation=[['home','Обзор',Compass],['card','Что делать',ListChecks],['question','Гиды и вопросы',BookOpen],['form','Документы и формы',Files],['service','Сервисы и инструменты',Wrench],['plan','Мой план',CalendarDays],['favorites','Избранное',Bookmark],['notifications','Уведомления',Bell]];
export function useRoute(){const [hash,set]=useState(location.hash);useEffect(()=>{const fn=()=>set(location.hash);addEventListener('hashchange',fn);return()=>removeEventListener('hashchange',fn)},[]);const [path,query='']=hash.replace(/^#\/?/,'').split('?');return {path:path||'home',params:new URLSearchParams(query)};}
export const go=(path,params={})=>{const q=new URLSearchParams(Object.entries(params).filter(([,v])=>v!==''&&v!=null));location.hash='/'+path+(q.size?'?'+q:'');};
export function App(){
 const route=useRoute(),[user,setUser]=useState(null),[catalog,setCatalog]=useState([]),[menu,setMenu]=useState(false),[message,setMessage]=useState(''),[personal,setPersonal]=useState({items:[],notifications:[]});
 const notify=s=>{setMessage(s);setTimeout(()=>setMessage(''),6500)};
 const refresh=()=>api('/api/personal').then(setPersonal).catch(e=>notify(e.message));
 useEffect(()=>{api('/api/me').then(x=>setUser(x.user));api('/api/catalog').then(setCatalog).catch(e=>notify(e.message));},[]);
 useEffect(()=>{if(user)refresh();else setPersonal({items:[],notifications:[]});},[user]);
 useEffect(()=>{setMenu(false);window.scrollTo(0,0)},[route.path]);
 const profession=route.params.get('profession')||'';
 const authProps={user,personal,refresh,notify,catalog};
 return <><a href="#main" className="skip">К содержанию</a><aside className={menu?'sidebar open':'sidebar'}><a className="brand" href="#/home"><span className="brand-mark"><Compass size={27}/></span><span>Навигатор<small>профессий</small></span></a><div className="side-label">ПРАВО В ВАШЕЙ РАБОТЕ</div><nav>{navigation.filter(([id])=>!mirror||!['plan','favorites','notifications'].includes(id)).map(([id,label,Icon])=><a key={id} className={route.path===id?'active':''} href={'#/'+id}><Icon size={19}/>{label}</a>)}{!mirror&&['editor','admin'].includes(user?.role)&&<a className={route.path.startsWith('admin')?'active':''} href="#/admin"><Settings size={19}/>Редакторский кабинет</a>}</nav><div className="side-bottom"><span className="live-dot"/>{mirror?'Публичная версия для просмотра':'Серверное приложение'}<p>{mirror?'Поиск, инструкции и документы.':'План и правки сохраняются в базе.'}</p></div></aside>
 <div className="workspace"><header className="topbar"><button className="mobile-toggle" aria-label="Открыть меню" onClick={()=>setMenu(!menu)}><Menu/></button><span>Профессиональный правовой справочник</span>{!mirror&&(user?<button onClick={async()=>{await api('/api/logout',{method:'POST'});setUser(null);go('home')}}>{user.username} · Выйти</button>:<button onClick={()=>go('login')}><LogIn size={16}/>Войти</button>)}{mirror&&<span className="pill">Только чтение</span>}</header>
 <main id="main" tabIndex={-1}>{route.path==='login'?<Login onLogin={u=>{setUser(u);go('home')}} notify={notify}/>:route.path.startsWith('item/')?<Detail id={route.path.slice(5)} route={route} {...authProps}/>:route.path.startsWith('admin')?<Admin route={route} {...authProps}/>:['plan','favorites','notifications'].includes(route.path)?<Personal section={route.path} {...authProps}/>:<Catalog route={route} catalog={catalog} profession={profession} notify={notify}/>}</main><footer>Навигатор профессий <span>Материалы источников · Правовая актуальность отмечена в каждой записи</span></footer></div>{message&&<div className="toast" role="status">{message}</div>}</>;
}
function Login({onLogin,notify}){return <section className="login panel"><span className="eyebrow">ЛИЧНОЕ ПРОСТРАНСТВО</span><h1>Вход в навигатор</h1><p>План, избранное и доступ к редакторским материалам.</p><form onSubmit={async e=>{e.preventDefault();const d=new FormData(e.currentTarget);try{const r=await api('/api/login',{method:'POST',body:Object.fromEntries(d)});onLogin(r.user)}catch(e){notify(e.message)}}}><label>Логин<input name="username" autoComplete="username" required/></label><label>Пароль<input name="password" type="password" autoComplete="current-password" required/></label><button className="primary">Войти</button></form></section>}
function Catalog({route,catalog,profession,notify}){
 const [result,setResult]=useState({items:[],total:0}),[busy,setBusy]=useState(true),[facets,setFacets]=useState([]);const q=route.params.get('q')||'',kind=route.path==='home'?'':route.path,page=Number(route.params.get('page'))||1;const prof=catalog.find(p=>p.id===profession);
 useEffect(()=>{let active=true;setBusy(true);api('/api/materials?'+new URLSearchParams({...Object.fromEntries(route.params),kind,limit:18})).then(r=>{if(active)setResult(r)}).catch(e=>notify(e.message)).finally(()=>active&&setBusy(false));return()=>{active=false}},[route.path,route.params.toString()]);
 useEffect(()=>{if(kind==='card')api('/api/materials?'+new URLSearchParams({kind,profession,limit:1000})).then(r=>setFacets(r.items)).catch(()=>{})},[kind,profession]);
 const filter=(key,value)=>go(route.path,{...Object.fromEntries(route.params),page:1,[key]:value});
 return <><div className="page-intro"><span className="eyebrow">{route.path==='home'?'ОТ ВОПРОСА К ДЕЙСТВИЮ':'БИБЛИОТЕКА НАВИГАТОРА'}</span><h1>{route.path==='home'?'Разобраться. Действовать.':navigation.find(x=>x[0]===route.path)?.[1]}</h1><p>{route.path==='home'?'Найдите свою ситуацию, пройдите шаги и подготовьте документы.':'Материалы по вашей профессии с указанием источников и статуса проверки.'}</p></div>
 <form className="searchbox" onSubmit={e=>{e.preventDefault();filter('q',new FormData(e.currentTarget).get('q'))}}><Search size={23}/><input key={q} name="q" aria-label="Поиск по ситуации" defaultValue={q} placeholder="Ситуация, вопрос или код карточки, например GD-A-01"/><button className="primary">Найти <ArrowRight size={17}/></button></form>
 <div className="filters"><label>Профессия<select aria-label="Профессия" value={profession} onChange={e=>filter('profession',e.target.value)}><option value="">Все направления</option>{catalog.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select></label><label>Порядок<select value={route.params.get('sort')||'asc'} onChange={e=>filter('sort',e.target.value)}><option value="asc">По названию: А–Я</option><option value="desc">По названию: Я–А</option></select></label>{kind==='card'&&['side','urgency'].map((k,i)=><label key={k}>{i?'Срочность':'Сторона'}<select value={route.params.get(k)||''} onChange={e=>filter(k,e.target.value)}><option value="">Все значения</option>{[...new Set(facets.map(m=>m[k]).filter(Boolean))].map(v=><option key={v} value={v}>{v}</option>)}</select></label>)}{q&&<button onClick={()=>filter('q','')}>Сбросить поиск</button>}</div>
 {route.path==='home'&&!q&&!profession&&<section className="professions"><div className="section-heading"><h2>Выберите направление</h2><span>{catalog.length} профессий и направлений</span></div><div className="profession-grid">{catalog.map((p,i)=><button key={p.id} onClick={()=>filter('profession',p.id)}><span className="profession-number">{String(i+1).padStart(2,'0')}</span><strong>{p.title}</strong><span className="profession-note">{p.status==='missing'?'Материалы не найдены':p.status==='assignment_only'?'Материалы готовятся':p.status==='guide_draft'?'Требует редакторской проверки':'Открыть материалы'}</span><ArrowUpRight size={18}/></button>)}</div></section>}
 {prof&&<div className="notice"><strong>{prof.title}</strong><p>{prof.note}</p>{prof.subprofessions&&<p>{prof.subprofessions.join(' · ')}</p>}</div>}
 <div className="section-heading"><h2>{q?'Результаты поиска':'Доступные материалы'}</h2><span>{busy?'Загрузка…':`${result.total} записей`}</span></div>
 {busy?<div className="loading" role="status">Загружаем материалы…</div>:result.items.length?<div className="material-list">{result.items.map(m=><MaterialRow key={m.id} m={m} back={location.hash}/>)}</div>:<div className="empty"><BookOpen size={34}/><h2>{q?'Ничего не найдено':'Материалы готовятся'}</h2><p>{q?'Попробуйте другую формулировку или сбросьте фильтры.':'Для этого раздела пока нет опубликованных материалов. Исходники и задачи доступны редактору.'}</p><button onClick={()=>go('home')}>Все направления</button></div>}
 {result.total>18&&<div className="pagination"><button disabled={page===1} onClick={()=>filter('page',page-1)}>Назад</button><span>{page} / {Math.ceil(result.total/18)}</span><button disabled={page*18>=result.total} onClick={()=>filter('page',page+1)}>Далее</button></div>}</>;
}
export function MaterialRow({m,back}){return <a className="material-row" href={'#/item/'+m.id+(back?'?back='+encodeURIComponent(back):'')}><span className="material-icon">{m.kind==='form'?<Files/>:m.kind==='card'?<ListChecks/>:<BookOpen/>}</span><div><div className="meta"><span>{labels[m.kind]}</span>{m.code&&<code>{m.code}</code>}</div><h3>{m.title}</h3><p>{(m.situation||m.simple||m.legal||m.blocks?.find(b=>b.text)?.text||'').slice(0,170)}</p></div><ArrowUpRight size={19}/></a>}
function Personal({section,user,personal,refresh,notify}){
 const [saved,setSaved]=useState([]);useEffect(()=>{Promise.all(personal.items.filter(x=>section==='favorites'?x.kind==='favorite':x.kind==='progress').map(x=>api('/api/materials/'+x.item).then(m=>({...m,progress:x.data})).catch(()=>null))).then(x=>setSaved(x.filter(Boolean)))},[section,personal]);
 if(mirror||!user)return <div className="empty"><h1>Ваше личное пространство</h1><p>{mirror?'Откройте серверное приложение для сохранения плана.':'Войдите, чтобы сохранять прогресс и задачи.'}</p>{!mirror&&<button onClick={()=>go('login')}>Войти</button>}</div>;
 const update=async(path,body,method='PUT')=>{try{await api(path,{method,body});refresh()}catch(e){notify(e.message)}};
 return <><span className="eyebrow">ЛИЧНОЕ ПРОСТРАНСТВО</span><h1>{navigation.find(x=>x[0]===section)?.[1]}</h1>{section==='notifications'?<>{personal.notifications.length?personal.notifications.map(n=><div className="panel" key={n.id}><h2>{n.title}</h2><p>{n.read?'Прочитано':'Новое уведомление'}</p>{n.materialId&&<a href={'#/item/'+n.materialId}>Открыть материал</a>}<button disabled={!!n.read} onClick={()=>update('/api/notifications/'+n.id,{})}>Отметить прочитанным</button></div>):<p className="empty">Новых уведомлений нет. Здесь появятся обновления избранного и сроки личных задач.</p>}</>:<>{saved.map(m=><div key={m.id}><MaterialRow m={m}/>{section==='plan'&&<p className="progress-caption">Выполнено {m.progress.done?.length||0} из {m.steps.length} · <a href={'#/item/'+m.id+'?step='+(m.progress.current||0)}>Продолжить с последнего шага</a></p>}</div>)}{!saved.length&&<p className="notice">{section==='plan'?'Начните инструкцию и отметьте первый шаг.':'Добавляйте материалы в избранное на странице вопроса или инструкции.'}</p>}{section==='plan'&&<><h2>Собственные задачи</h2><form className="panel task-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);update('/api/personal/task/'+crypto.randomUUID(),{title:f.get('title'),due:f.get('due'),done:false});e.currentTarget.reset()}}><label>Задача<input name="title" required/></label><label>Мой срок<input name="due" type="date"/></label><button className="primary">Добавить</button><small>Выбранный вами срок. Правовой дедлайн автоматически не рассчитывается.</small></form>{personal.items.filter(x=>x.kind==='task').map(t=><div className="task panel" key={t.item}><label><input type="checkbox" checked={!!t.data.done} onChange={e=>update('/api/personal/task/'+t.item,{...t.data,done:e.target.checked})}/>{t.data.title}</label><span>{t.data.due||'Без срока'}{!t.data.done&&t.data.due&&t.data.due<new Date().toISOString().slice(0,10)?' · Просрочена':''}</span><button onClick={()=>update('/api/personal/task/'+t.item,null,'DELETE')}>Удалить</button></div>)}</>}</>}</>;
}
createRoot(document.getElementById('root')).render(<App/>);
