import React,{useState,useEffect} from 'react';
import {ArrowLeft,ArrowRight,Bookmark,Check,Download,Printer,Link,ExternalLink} from 'lucide-react';
import {api,fileUrl,mirror,labels} from './api';
export function Blocks({blocks=[]}){return <div className="source-text">{blocks.map((b,i)=>b.rows?<div className="table-scroll" key={i}><table><tbody>{b.rows.map((r,j)=><tr key={j}>{r.map((c,k)=><td key={k}>{c}</td>)}</tr>)}</tbody></table></div>:b.text?<p key={i}>{b.text}</p>:null)}</div>}
export function FileLink({id,name}){return <div className="file-link"><div><strong>{name||id}</strong><small>Оригинальный файл из комплекта</small></div><a href={fileUrl(id)} target="_blank" rel="noreferrer">Открыть оригинал <ExternalLink size={15}/></a><a href={fileUrl(id,true)} download>Скачать <Download size={15}/></a></div>}
export function Detail({id,route,user,personal,refresh,notify}){
 const [m,setM]=useState(null),[failure,setFailure]=useState(''),[register,setRegister]=useState('simple'),[relations,setRelations]=useState([]);const step=route.params.has('step')?Number(route.params.get('step')):null;
 useEffect(()=>{setM(null);setFailure('');api('/api/materials/'+id).then(setM).catch(e=>setFailure(e.message));api('/api/relations/'+id).then(setRelations).catch(()=>{})},[id]);
 if(failure)return <div className="empty"><h1>Материал недоступен</h1><p>{failure}</p><a href="#/home">Вернуться в каталог</a></div>;
 if(!m)return <div className="loading">Загружаем материал…</div>;
 const progress=personal.items.find(x=>x.kind==='progress'&&x.item===id)?.data||{done:[],current:0};const favorite=personal.items.some(x=>x.kind==='favorite'&&x.item===id);const current=m.steps[step];
 const save=async(kind,data,method='PUT')=>{if(!user){notify('Войдите для сохранения в профиле');return;}try{await api('/api/personal/'+kind+'/'+id,{method,body:data});refresh();notify('Сохранено в профиле')}catch(e){notify(e.message)}};
 const toStep=i=>{const p=new URLSearchParams(route.params);p.set('step',i);location.hash='/item/'+id+'?'+p;if(user)save('progress',{...progress,current:i});};
 return <article className="detail"><a className="back-link" href={route.params.get('back')?.startsWith('#/')?route.params.get('back'):'#/card'}><ArrowLeft size={17}/>К результатам</a><div className="meta"><span>{labels[m.kind]}</span>{m.code&&<code>{m.code}</code>}<span>{labels[m.status]}</span></div><h1>{m.title}</h1><div className="detail-tools">{!mirror&&<button onClick={()=>save('favorite',{},favorite?'DELETE':'PUT')}><Bookmark size={17}/>{favorite?'Убрать из избранного':'В избранное'}</button>}<button onClick={()=>window.print()}><Printer size={17}/>Печать</button><button onClick={()=>navigator.clipboard.writeText(location.href).then(()=>notify('Ссылка скопирована')).catch(()=>notify('Скопируйте адрес из строки браузера'))}><Link size={17}/>Ссылка</button>{['editor','admin'].includes(user?.role)&&<a href={'#/admin/edit/'+id}>Редактировать</a>}</div>
 <div className="legal-status">{m.legalStatus==='verified'?`Проверено ${m.legalDate}. ${m.legalBasis}`:'Правовая актуальность не проверена. Текст перенесён из предоставленного источника.'}{m.sourceDate&&<small>Дата в источнике: {m.sourceDate}</small>}</div>
 {m.kind==='card'&&<><section className="print-steps"><h2>Полная инструкция</h2>{m.steps.map((s,i)=><div key={s.id}><h3>Шаг {i+1}</h3><p className="preserve">{s.text}</p>{s.important&&<p>Важно: {s.important}</p>}{s.reference&&<p>Справочно: {s.reference}</p>}</div>)}</section><div className="overview-grid"><section className="panel"><span className="eyebrow">СИТУАЦИЯ</span><p>{m.situation||m.title}</p>{m.audience&&<p><b>Кому:</b> {m.audience}</p>}{m.side&&<p><b>Сторона:</b> {m.side}</p>}{m.scope&&<p><b>Границы применения:</b> {m.scope}</p>}</section><section className="panel"><span className="eyebrow">СРОКИ ПО ИСТОЧНИКУ</span><p>{m.urgency||'Срочность не указана'}</p><p className="preserve">{m.deadlines||'Отдельное правило срока не выделено. См. шаги.'}</p></section></div>
 {m.steps.length>0&&<><div className="section-heading"><h2>Порядок действий</h2><span>{m.steps.length} шагов</span></div><div className="step-rail">{m.steps.map((s,i)=><button className={step===i?'selected':''} key={s.id} onClick={()=>toStep(i)} aria-label={'Шаг '+(i+1)}>{progress.done.includes(s.id)?<Check size={17}/>:i+1}</button>)}</div>{current?<section className="panel active-step"><span className="eyebrow">ШАГ {step+1} ИЗ {m.steps.length}</span><p className="step-text">{current.text}</p>{current.important&&<div className="notice"><b>Важно</b><p>{current.important}</p></div>}{current.reference&&<div className="notice"><b>Справочно</b><p>{current.reference}</p></div>}{current.branches?.filter(b=>m.steps[b.index]).map((b,i)=><button key={i} onClick={()=>toStep(b.index)}>{b.label}</button>)}{current.attachments?.map(f=><FileLink key={f} id={f}/>)}{!mirror&&<button className="primary" onClick={()=>save('progress',{current:step,done:progress.done.includes(current.id)?progress.done.filter(x=>x!==current.id):[...progress.done,current.id]})}><Check size={18}/>{progress.done.includes(current.id)?'Шаг выполнен · отменить':'Отметить выполненным'}</button>}<div className="pagination"><button disabled={step===0} onClick={()=>toStep(step-1)}>Предыдущий шаг</button><button disabled={step===m.steps.length-1} onClick={()=>toStep(step+1)}>Следующий шаг <ArrowRight size={16}/></button></div></section>:<><ol className="step-overview">{m.steps.map((s,i)=><li key={s.id}><button onClick={()=>toStep(i)}>{s.text.split(/(?<=\.)\s/)[0]}</button></li>)}</ol><button className="primary" onClick={()=>toStep(progress.current||0)}>Пройти по шагам <ArrowRight size={18}/></button></>}</>}
 {m.documents&&<section className="panel"><h2>Что подготовить</h2><p className="preserve">{m.documents}</p></section>}{m.errors&&<section className="panel warning"><h2>Чего не делать</h2><p className="preserve">{m.errors}</p></section>}{m.norms&&<details className="panel"><summary>Правовое основание</summary><p className="preserve">{m.norms}</p></details>}</>}
 {m.kind==='question'&&(m.legal||m.simple)?<><div className="segmented"><button className={register==='simple'?'selected':''} onClick={()=>setRegister('simple')}>Простыми словами</button><button className={register==='legal'?'selected':''} onClick={()=>setRegister('legal')}>Юридически точно</button><button className={register==='both'?'selected':''} onClick={()=>setRegister('both')}>Рядом</button></div><div className={register==='both'?'overview-grid':''}>{(register==='both'?['legal','simple']:[register]).map(r=><section className="panel" key={r}><h2>{r==='legal'?'Юридически точно':'Простыми словами'}</h2><p className="preserve">{m[r]||'Этот регистр ответа ещё не выделен редактором.'}</p></section>)}</div></>:!['card','form'].includes(m.kind)&&<section className="panel"><Blocks blocks={m.blocks}/></section>}
 {m.kind==='service'&&m.url&&<div className="notice">Адрес из источника, доступность не проверена: <a href={m.url} target="_blank" rel="noreferrer">{m.url}</a></div>}
 {m.fileId&&<><FileLink id={m.fileId} name={m.title}/>{m.sourceName?.endsWith('.pdf')&&<iframe title={'Просмотр '+m.title} src={fileUrl(m.fileId)} className="pdf-view"/>}{!m.sourceName?.endsWith('.pdf')&&<p>Формат DOCX: скачайте оригинал для просмотра в Word.</p>}</>}
 {m.attachments?.length>0&&<section><h2>Связанные документы</h2>{m.attachments.map(f=><FileLink key={f} id={f}/>)}</section>}
 {relations.length>0&&<section className="panel"><h2>Связанные материалы</h2>{relations.map(r=><p key={r.id}>{r.target?<a href={'#/item/'+r.target}>{r.target_code}</a>:<span>{r.target_code} · связанный материал пока не опубликован</span>}</p>)}</section>}
 <details className="panel"><summary>Источник и полный фрагмент</summary><p>{m.sourceName||'Создано редактором'} · {m.sourceId}</p><Blocks blocks={m.blocks}/></details></article>;
}
