import React,{useState,useEffect,useRef} from 'react';
import {ArrowLeft,ArrowRight,Bookmark,Check,Download,Printer,Link,Eye,FileText} from 'lucide-react';
import {api,fileUrl,mirror,labels} from './api';
export function Blocks({blocks=[]}){return <div className="source-text">{blocks.map((b,i)=>b.rows?<div className="table-scroll" key={i}><table><tbody>{b.rows.map((r,j)=><tr key={j}>{r.map((c,k)=><td key={k}>{c}</td>)}</tr>)}</tbody></table></div>:b.text?<p key={i}>{b.text}</p>:null)}</div>}
let formCatalog;
export function FileLink({id,name}){
 const [file,setFile]=useState(null);
 useEffect(()=>{formCatalog ||= api('/api/materials?kind=form&limit=1000');formCatalog.then(r=>setFile(r.items.find(m=>m.fileId===id))).catch(()=>{})},[id]);
 const pdf=file?.sourceName?.toLowerCase().endsWith('.pdf');
 return <div className="file-link"><span className="file-symbol"><FileText size={28}/></span><div><strong>{name||file?.title||'Документ'}</strong><div className="file-actions">{pdf&&<a href={fileUrl(id)} target="_blank" rel="noreferrer"><Eye size={20}/>Просмотреть</a>}<a href={fileUrl(id,true)} download><Download size={20}/>{pdf?'Скачать':file?.sourceName?.toLowerCase().endsWith('.docx')?'Скачать DOCX':'Скачать файл'}</a></div></div></div>;
}
const stepTitle=s=>s.text.replace(/^\d+[.)]\s*/,'').split(/(?<=\.)\s/)[0];
export function Detail({id,route,user,personal,refresh,notify}){
 const [m,setM]=useState(null),[failure,setFailure]=useState(''),[register,setRegister]=useState('simple'),[relations,setRelations]=useState([]),rail=useRef(null);
 const cardView=route.params.get('view')==='card';
 const progress=personal.items.find(x=>x.kind==='progress'&&x.item===id)?.data||{done:[],current:0};
 const requested=route.params.has('step')?Number(route.params.get('step')):progress.current||0;
 const step=m?.steps?.length&&!cardView?Math.max(0,Math.min(m.steps.length-1,Number.isFinite(requested)?requested:0)):null;
 useEffect(()=>{setM(null);setFailure('');api('/api/materials/'+id).then(setM).catch(e=>setFailure(e.message));api('/api/relations/'+id).then(setRelations).catch(()=>{})},[id]);
 useEffect(()=>{const active=rail.current?.querySelector('[aria-current="step"]');if(active)rail.current.scrollTo({left:active.offsetLeft-rail.current.offsetLeft,behavior:'instant'})},[step,m]);
 if(failure)return <div className="empty"><h1>Материал недоступен</h1><p>{failure}</p><a href="#/account">Открыть личный кабинет</a><p><a href="#/home">К списку</a></p></div>;
 if(!m)return <div className="loading">Загрузка…</div>;
 if(m.locked)return <div className="empty"><h1>{m.title}</h1><p>Материал доступен по подписке в серверном приложении.</p><a href="#/home">К списку</a></div>;
 const favorite=personal.items.some(x=>x.kind==='favorite'&&x.item===id),current=m.steps[step];
 const back=route.params.get('back')?.startsWith('#/')?route.params.get('back'):'#/home'+(m.profession?'?profession='+m.profession:'');
 const save=async(kind,data,method='PUT')=>{if(!user){notify('Войдите, чтобы сохранить изменения');return;}try{await api('/api/personal/'+kind+'/'+id,{method,body:data});refresh();notify('Сохранено')}catch(e){notify(e.message)}};
 const toStep=i=>{const p=new URLSearchParams(route.params);p.delete('view');p.set('step',i);location.hash='/item/'+id+'?'+p;if(user)save('progress',{...progress,current:i})};
 const tools=<div className="detail-tools">{!mirror&&<button onClick={()=>save('favorite',{},favorite?'DELETE':'PUT')}><Bookmark size={18}/>{favorite?'Убрать из избранного':'В избранное'}</button>}<button onClick={()=>window.print()}><Printer size={18}/>Печать</button><button onClick={()=>navigator.clipboard.writeText(location.href).then(()=>notify('Ссылка скопирована')).catch(()=>notify('Скопируйте адрес из строки браузера'))}><Link size={18}/>Ссылка</button>{['editor','admin'].includes(user?.role)&&<a href={'#/admin/edit/'+id}>Редактировать</a>}</div>;
 return <article className={'detail'+(current?' step-mode':'')}>{m.steps.length>0&&!cardView&&<div className="step-navigation"><button aria-label="Предыдущий этап" disabled={step===0} onClick={()=>toStep(step-1)}><ArrowLeft/></button><div className="step-rail" ref={rail}>{m.steps.map((s,i)=><button className={step===i?'selected':''} aria-current={step===i?'step':undefined} key={s.id} onClick={()=>toStep(i)} aria-label={'Шаг '+(i+1)+'. '+stepTitle(s)}><span>{progress.done.includes(s.id)?<Check size={17}/>:i+1}</span><span>{stepTitle(s)}</span></button>)}</div><button aria-label="Следующий этап" disabled={step===m.steps.length-1} onClick={()=>toStep(step+1)}><ArrowRight/></button></div>}
 <div className="instruction-sheet"><header className="instruction-heading"><div className="meta">{m.code&&<code>{m.code}</code>}{m.status!=='published'&&<span>{labels[m.status]}</span>}</div><h1>{m.title}</h1>{current&&<h2 className="step-subtitle">{stepTitle(current)}</h2>}{tools}</header><p className="source-label">{m.contentOrigin==='editorial'?'Редакционная памятка · новый материал':m.contentOrigin==='edited-source'?'Материал из комплекта с редакционным дополнением':m.sourceId?'Материал из исходного комплекта':'Материал редактора'}</p>{m.legalStatus!=='verified'&&<p className="content-warning">Перед применением проверьте действующие нормы и условия вашей ситуации.{m.profession==='medicine'&&' Карточка не заменяет клинические рекомендации и медицинское решение.'}</p>}
 {m.legalReview&&<details className="panel legal-review"><summary>Правовая правка от {m.legalReview.date}</summary><p>{m.legalReview.issue}</p><p>Проверены указанные положения. Полная юридическая проверка материала не завершена.</p>{m.legalReview.sources.map((s,i)=><p key={i}><a href={s.url} target="_blank" rel="noreferrer">{s.label}</a></p>)}</details>}
 {m.kind==='form'&&<p className="content-warning">Файл из исходного комплекта. Актуальность редакции формы отдельно не подтверждена; перед подачей сверьте её с формой принимающего органа.</p>}
 {m.kind==='card'&&<><section className="print-steps"><h2>Инструкция</h2>{m.steps.map((s,i)=><div key={s.id}><h3>Шаг {i+1}</h3><p className="preserve">{s.text}</p>{s.important&&<p>Важно: {s.important}</p>}{s.reference&&<p>Справочно: {s.reference}</p>}</div>)}</section>
 {cardView?<div className="problem-solution"><section className="problem"><h2>{m.errors?'Ошибка':'Ситуация'}</h2><div><p className="preserve">{m.errors||m.situation||m.title}</p></div></section><section className="solution"><h2>Решение</h2><div><ol>{m.steps.map((s,i)=><li key={s.id}><button onClick={()=>toStep(i)}>{stepTitle(s)}</button></li>)}</ol><button className="primary" onClick={()=>toStep(0)}>Перейти к инструкции</button></div></section></div>:current?<section className="active-step">{current.attachments?.map(f=><FileLink key={f} id={f}/>)}<div className="step-content"><p className="step-text">{current.text}</p>{current.important&&<div className="notice important"><b>Важно</b><p>{current.important}</p></div>}{current.reference&&<div className="notice reference"><b>Справочно</b><p>{current.reference}</p></div>}{current.branches?.filter(b=>m.steps[b.index]).map((b,i)=><button key={i} onClick={()=>toStep(b.index)}>{b.label}</button>)}</div>{!mirror&&<label className="complete-step"><input type="checkbox" checked={progress.done.includes(current.id)} onChange={()=>save('progress',{current:step,done:progress.done.includes(current.id)?progress.done.filter(x=>x!==current.id):[...progress.done,current.id]})}/>Шаг выполнен</label>}</section>:<p>Порядок действий ещё не подготовлен.</p>}
 <div className="instruction-bottom"><a className="back-link" href={back}><ArrowLeft size={20}/>К списку</a>{current&&<div><button disabled={step===0} onClick={()=>toStep(step-1)}>Предыдущий шаг</button><button disabled={step===m.steps.length-1} onClick={()=>toStep(step+1)}>Следующий шаг</button></div>}</div>
 <details className="panel"><summary>Ситуация, условия и сроки</summary><p>{m.situation}</p>{m.audience&&<p><b>Кому:</b> {m.audience}</p>}{m.side&&<p><b>Сторона:</b> {m.side}</p>}{m.scope&&<p><b>Область применения:</b> {m.scope}</p>}<p>{m.urgency}</p><p className="preserve">{m.deadlines}</p></details>
 {m.documents&&<details className="panel"><summary>Что подготовить</summary><p className="preserve">{m.documents}</p></details>}{m.errors&&!cardView&&<details className="panel warning"><summary>Чего не делать</summary><p className="preserve">{m.errors}</p></details>}{m.norms&&<details className="panel"><summary>Правовое основание</summary><p className="preserve">{m.norms}</p></details>}</>}
 {m.kind==='question'&&(m.legal||m.simple)?<><div className="segmented"><button className={register==='simple'?'selected':''} onClick={()=>setRegister('simple')}>Простыми словами</button><button className={register==='legal'?'selected':''} onClick={()=>setRegister('legal')}>Правовой разбор</button><button className={register==='both'?'selected':''} onClick={()=>setRegister('both')}>Оба варианта</button></div><div className={register==='both'?'overview-grid':''}>{(register==='both'?['legal','simple']:[register]).map(r=><section className="panel" key={r}><h2>{r==='legal'?'Правовой разбор':'Простыми словами'}</h2><p className="preserve">{m[r]||'Ответ ещё не подготовлен.'}</p></section>)}</div></>:!['card','form'].includes(m.kind)&&<section className="panel"><Blocks blocks={m.blocks}/></section>}
 {m.kind==='service'&&m.url&&<div className="notice">Ссылка из материала, доступность не проверена: <a href={m.url} target="_blank" rel="noreferrer">{m.url}</a></div>}
 {m.fileId&&<><FileLink id={m.fileId} name={m.title}/>{m.sourceName?.endsWith('.pdf')&&<iframe title={'Просмотр '+m.title} src={fileUrl(m.fileId)} className="pdf-view"/>}{!m.sourceName?.endsWith('.pdf')&&<p>Документ открывается в Word.</p>}</>}
 {m.attachments?.length>0&&<details className="panel"><summary>Документы инструкции</summary>{m.attachments.map(f=><FileLink key={f} id={f}/>)}</details>}
 {relations.length>0&&<details className="panel"><summary>Связанные материалы</summary>{relations.map(r=><p key={r.id}>{r.target?<a href={'#/item/'+r.target}>{r.target_code}</a>:<span>{r.target_code} · не опубликован</span>}</p>)}</details>}
 {m.externalLinks?.filter(l=>/^https?:\/\//.test(l.url)).length>0&&<details className="panel"><summary>Ссылки для проверки</summary>{m.externalLinks.filter(l=>/^https?:\/\//.test(l.url)).map((l,i)=><p key={i}><a href={l.url} target="_blank" rel="noreferrer">{l.label||l.url}</a></p>)}</details>}<p className="legal-status">{m.legalStatus==='verified'?`Проверено ${m.legalDate}. ${m.legalBasis}`:'Актуальность норм требует проверки.'}{m.sourceDate&&<span> Дата в источнике: {m.sourceDate}</span>}</p>
 <details className="panel"><summary>Исходный материал</summary>{m.legalReview&&<p className="content-warning">Архивный текст до правки. Он может содержать ошибки, исправленные в инструкции выше.</p>}<p>{m.sourceName||'Материал редактора'} · {m.sourceId}</p><Blocks blocks={m.blocks}/></details>{m.kind!=='card'&&<a className="back-link" href={back}><ArrowLeft size={20}/>К списку</a>}</div></article>;
}
